// =====================================================================
// data_extra_v230c.js — v2.30 : suite (micro, macro, commerce, HPE, ML,
// suivi-évaluation, histoire/travail/santé/éducation, sciences sociales,
// culture générale & environnement).
// =====================================================================

const { D, mk, F } = require('./data_extra_v230b.js');

// ---------------- MICROÉCONOMIE (+56 → 60) --------------------------
const micro = [];
// Élasticité-prix (paramétrique) : %ΔQ / %ΔP
[[10,5,-2],[20,10,-2],[6,3,-2],[15,5,-3],[8,4,-2],[12,6,-2],[9,3,-3],[4,8,-0.5],[10,4,-2.5],[6,2,-3]]
.forEach(([dq, dp, e]) => micro.push(mk(
  `La quantité demandée baisse de ${dq} % quand le prix augmente de ${dp} %. L'élasticité-prix de la demande vaut :`,
  `${String(e).replace('.', ',')}`, `${String(-e).replace('.', ',')}`, `${String(e*2).replace('.', ',')}`, `${dq}`,
  `Élasticité = %ΔQ ÷ %ΔP = (−${dq}) ÷ (+${dp}) = ${String(e).replace('.', ',')}. Négative car demande et prix varient en sens inverse ; |e|>1 = demande élastique.`,
  'https://fr.wikipedia.org/wiki/%C3%89lasticit%C3%A9_(%C3%A9conomie)')));
[
 mk('En concurrence pure et parfaite, l\'entreprise est…','Preneuse de prix (price taker)','Faiseuse de prix','En situation de monopole','Subventionnée',
   'Atomicité, homogénéité, libre entrée, transparence et mobilité : chaque agent est trop petit pour influencer le prix de marché.',
   'https://fr.wikipedia.org/wiki/Concurrence_pure_et_parfaite'),
 mk('L\'équilibre du consommateur est atteint lorsque…','Le taux marginal de substitution égale le rapport des prix','L\'utilité totale est nulle','Le revenu est épuisé en un seul bien','Les prix sont égaux',
   'Le consommateur maximise son utilité sous contrainte budgétaire : la courbe d\'indifférence est tangente à la droite de budget (TMS = p₁/p₂).',
   'https://fr.wikipedia.org/wiki/Th%C3%A9orie_du_consommateur'),
 mk('La loi des rendements marginaux décroissants stipule que…','L\'ajout d\'un facteur variable finit par accroître la production à un rythme décroissant','La production est toujours proportionnelle','Les coûts sont constants','Le profit est illimité',
   'À court terme, au-delà d\'un seuil, chaque unité supplémentaire de facteur variable (ex. travail) apporte une production additionnelle plus faible.',
   'https://fr.wikipedia.org/wiki/Rendements_d%C3%A9croissants'),
 mk('Le coût marginal est…','Le coût de production d\'une unité supplémentaire','Le coût total moyen','Le coût fixe unitaire','La recette totale',
   'Cm = dCT/dQ. En concurrence, l\'entreprise produit jusqu\'où le coût marginal égale le prix (recette marginale).',
   'https://fr.wikipedia.org/wiki/Co%C3%BBt_marginal'),
 mk('Un monopole se caractérise par…','Un seul offreur face à de nombreux demandeurs','De nombreux offreurs','La gratuité','L\'absence de demande',
   'Le monopoleur, faiseur de prix, produit là où recette marginale = coût marginal, avec un prix supérieur au coût marginal (perte sèche pour la société).',
   'https://fr.wikipedia.org/wiki/Monopole'),
 mk('Le surplus du consommateur mesure…','La différence entre le prix maximal accepté et le prix payé','Le profit de l\'entreprise','La TVA collectée','Le coût de production',
   'Graphiquement, c\'est l\'aire sous la courbe de demande et au-dessus du prix : le gain net que le consommateur retire de l\'échange.',
   'https://fr.wikipedia.org/wiki/Surplus_du_consommateur'),
 mk('Un bien Giffen est un bien pour lequel…','La demande augmente quand le prix augmente','La demande est nulle','L\'offre est infinie','Le prix est fixe',
   'Cas extrême de bien inférieur où l\'effet revenu l\'emporte sur l\'effet substitution : la courbe de demande est croissante (rare, historique).',
   'https://fr.wikipedia.org/wiki/Bien_de_Giffen'),
 mk('L\'externalité négative (ex. pollution) conduit à…','Un coût social supérieur au coût privé, justifiant une intervention','Un marché toujours efficient','Une subvention automatique','La disparition de la demande',
   'Le marché sous-estime les coûts supportés par des tiers ; taxe pigouvienne, normes ou marché de droits internalisent l\'externalité.',
   'https://fr.wikipedia.org/wiki/Externalit%C3%A9'),
 mk('Un bien public pur est…','Non-rival et non-excluable (ex. défense nationale)','Vendu cher','Réservé aux riches','Toujours importé',
   'Non-rivalité (l\'usage de l\'un ne prive pas l\'autre) et non-exclusion (impossible d\'empêcher l\'accès) entraînent le problème du passager clandestin.',
   'https://fr.wikipedia.org/wiki/Bien_public'),
 mk('L\'optimum de Pareto est une situation où…','On ne peut améliorer le sort d\'un agent sans détériorer celui d\'un autre','Tout le monde est riche','Les prix sont nuls','L\'État possède tout',
   'Critère d\'efficacité allocative ; il ne dit rien sur l\'équité de la répartition, plusieurs optima de Pareto pouvant coexister.',
   'https://fr.wikipedia.org/wiki/Optimum_de_Pareto'),
 mk('L\'oligopole désigne un marché…','Dominé par un petit nombre de vendeurs interdépendants','Sans vendeur','Avec un seul acheteur','Parfaitement concurrentiel',
   'Les décisions des firmes sont stratégiquement liées ; la théorie des jeux (Cournot, Bertrand, Stackelberg) modélise leurs comportements.',
   'https://fr.wikipedia.org/wiki/Oligopole'),
 mk('Le monopsone est un marché où…','Il y a un seul acheteur face à plusieurs vendeurs','Il y a un seul vendeur','Les prix sont libres','L\'État est absent',
   'Symétrique du monopole côté demande (ex. employeur unique dans une localité), il permet à l\'acheteur de tirer les prix vers le bas.',
   'https://fr.wikipedia.org/wiki/Monopsone'),
 mk('La courbe d\'offre d\'une entreprise concurrentielle correspond…','À sa courbe de coût marginal au-dessus du coût variable moyen','À sa demande','À son coût fixe','À sa recette moyenne',
   'L\'entreprise produit tant que le prix couvre le coût variable moyen ; en dessous du minimum du CVM, elle ferme à court terme.',
   'https://fr.wikipedia.org/wiki/Courbe_d%27offre'),
 mk('Le TMS (taux marginal de substitution) mesure…','La quantité d\'un bien qu\'on cède pour une unité de l\'autre en gardant la même utilité','Le taux d\'intérêt','La TVA','Le prix relatif fixé par l\'État',
   'Le TMS est la pente (en valeur absolue) de la courbe d\'indifférence ; il décroît en général le long de la courbe (convexité des préférences).',
   'https://fr.wikipedia.org/wiki/Taux_marginal_de_substitution'),
 mk('L\'équilibre de Nash est atteint quand…','Chaque joueur choisit sa meilleure réponse aux stratégies des autres','Tous perdent','Un joueur domine tout','Le hasard décide',
   'Aucun joueur n\'a intérêt à dévier unilatéralement ; le dilemme du prisonnier illustre un équilibre de Nash sous-optimal.',
   'https://fr.wikipedia.org/wiki/%C3%89quilibre_de_Nash'),
 mk('Un bien inférieur est un bien dont…','La demande diminue quand le revenu augmente','La demande augmente avec le revenu','Le prix est toujours bas','L\'offre est illimitée',
   'À l\'inverse des biens normaux, l\'élasticité-revenu est négative (ex. produits de subsistance remplacés quand le revenu croît).',
   'https://fr.wikipedia.org/wiki/Bien_inf%C3%A9rieur'),
] .forEach(x => micro.push(x));
// Coût moyen (paramétrique)
[[100,500000,5000],[200,800000,4000],[50,300000,6000],[400,1200000,3000],[250,1000000,4000],[80,240000,3000],[500,2000000,4000],[120,360000,3000],[300,900000,3000],[150,600000,4000]]
.forEach(([q, ct, cm]) => micro.push(mk(
  `Une entreprise produit ${q} unités pour un coût total de ${F(ct)} FCFA. Son coût moyen unitaire est :`,
  `${F(cm)} FCFA`, `${F(cm*2)} FCFA`, `${F(Math.round(cm/2))} FCFA`, `${F(ct)} FCFA`,
  `Coût moyen = coût total ÷ quantité = ${F(ct)} ÷ ${q} = ${F(cm)} FCFA/unité.`,
  'https://fr.wikipedia.org/wiki/Co%C3%BBt_moyen')));

// ---------------- MACROÉCONOMIE (+56 → 60) --------------------------
const macro = [];
// Croissance du PIB (paramétrique)
[[1000,1050,5],[2000,2040,2],[500,540,8],[1500,1545,3],[800,880,10],[1200,1236,3],[3000,3150,5],[600,624,4],[2500,2600,4],[900,990,10]]
.forEach(([y0, y1, g]) => macro.push(mk(
  `Le PIB passe de ${F(y0)} à ${F(y1)} milliards FCFA en un an. Le taux de croissance est de :`,
  `${g} %`, `${g+2} %`, `${Math.round(g/2)} %`, `${y1-y0} %`,
  `Taux = (${F(y1)} − ${F(y0)}) ÷ ${F(y0)} = ${g} %. La croissance réelle corrige en plus de l'inflation.`,
  'https://fr.wikipedia.org/wiki/Produit_int%C3%A9rieur_brut')));
[
 mk('Le PIB mesure…','La valeur des biens et services finaux produits sur un territoire en un an','La richesse accumulée totale','La masse monétaire','Le nombre d\'habitants',
   'Le Produit Intérieur Brut est un flux annuel ; il peut se calculer par la production (valeurs ajoutées), les revenus ou les dépenses.',
   'https://fr.wikipedia.org/wiki/Produit_int%C3%A9rieur_brut'),
 mk('L\'équilibre emplois-ressources s\'écrit…','PIB + Importations = Consommation + Investissement + Dépenses publiques + Exportations','PIB = Impôts','PIB = Masse monétaire','Épargne = Impôts',
   'Ressources (production + importations) = emplois (C + I + G + X). Réarrangé, il fonde la comptabilité nationale.',
   'https://fr.wikipedia.org/wiki/%C3%89quilibre_emplois-ressources'),
 mk('Le multiplicateur keynésien indique que…','Une hausse initiale de dépense engendre une hausse plus que proportionnelle du revenu','Les dépenses n\'ont aucun effet','L\'épargne crée le revenu','Les impôts stimulent toujours',
   'k = 1/(1−c) où c est la propension marginale à consommer : les vagues successives de consommation amplifient l\'impulsion initiale.',
   'https://fr.wikipedia.org/wiki/Multiplicateur_keyn%C3%A9sien'),
 mk('Le chômage structurel résulte…','D\'une inadéquation durable entre qualifications et besoins','D\'une simple récession passagère','D\'un excès de main-d\'œuvre saisonnière','De congés payés',
   'Il tient aux mutations technologiques et sectorielles ; il se distingue du chômage conjoncturel (lié au cycle) et frictionnel (transitions).',
   'https://fr.wikipedia.org/wiki/Ch%C3%B4mage_structurel'),
 mk('La courbe de Phillips décrit à court terme…','Une relation inverse entre inflation et chômage','Une relation entre PIB et impôts','L\'égalité épargne-investissement','Le taux de change',
   'Historiquement, moins de chômage s\'accompagnait de plus d\'inflation ; la relation se dégrade avec la stagflation et les anticipations (Friedman-Phelps).',
   'https://fr.wikipedia.org/wiki/Courbe_de_Phillips'),
 mk('La politique budgétaire expansionniste consiste à…','Augmenter les dépenses publiques ou baisser les impôts pour soutenir la demande','Réduire la masse monétaire','Relever les taux directeurs','Baisser les salaires',
   'Elle stimule l\'activité en période de sous-emploi, au prix d\'un possible creusement du déficit et de la dette publique.',
   'https://fr.wikipedia.org/wiki/Politique_budg%C3%A9taire'),
 mk('Le modèle IS-LM représente l\'équilibre simultané…','Du marché des biens (IS) et du marché de la monnaie (LM)','Du commerce extérieur','Du marché du travail seul','Des changes',
   'Développé par Hicks à partir de Keynes, il croise la courbe IS (investissement-épargne) et LM (liquidité-monnaie) pour déterminer revenu et taux d\'intérêt.',
   'https://fr.wikipedia.org/wiki/Mod%C3%A8le_IS-LM'),
 mk('La stagflation combine…','Stagnation (faible croissance, chômage) et inflation','Croissance forte et plein emploi','Déflation et boom','Excédent et récession',
   'Phénomène des années 1970 (chocs pétroliers) qui a remis en cause l\'arbitrage keynésien inflation-chômage.',
   'https://fr.wikipedia.org/wiki/Stagflation'),
 mk('La balance commerciale est excédentaire quand…','Les exportations de biens dépassent les importations','Les importations dépassent les exportations','Les impôts dépassent les dépenses','L\'épargne est nulle',
   'Composante de la balance des paiements ; un excédent commercial contribue positivement au PIB via les exportations nettes.',
   'https://fr.wikipedia.org/wiki/Balance_commerciale'),
 mk('L\'effet d\'éviction désigne…','La réduction de l\'investissement privé provoquée par la hausse des taux liée au déficit public','La fuite des capitaux','La baisse des exportations','L\'inflation importée',
   'Un financement public accru peut pousser les taux d\'intérêt à la hausse et « évincer » l\'emprunt des entreprises et ménages.',
   'https://fr.wikipedia.org/wiki/Effet_d%27%C3%A9viction'),
 mk('Le taux de chômage se calcule par…','Chômeurs ÷ population active','Chômeurs ÷ population totale','Actifs ÷ inactifs','Emplois ÷ entreprises',
   'La population active = actifs occupés + chômeurs (au sens du BIT : sans emploi, disponibles et en recherche).',
   'https://fr.wikipedia.org/wiki/Taux_de_ch%C3%B4mage'),
 mk('La déflation est…','Une baisse durable et généralisée des prix','Une hausse des prix','Une dévaluation','Une baisse des salaires uniquement',
   'Dangereuse car elle alourdit le poids réel des dettes et incite à reporter les achats (spirale récessive).',
   'https://fr.wikipedia.org/wiki/D%C3%A9flation'),
 mk('Les critères de convergence de l\'UEMOA incluent notamment…','Déficit ≤ 3 % du PIB et dette ≤ 70 % du PIB','Croissance ≥ 10 %','Chômage ≤ 2 %','Exportations ≥ importations',
   'Le pacte vise la stabilité macroéconomique : déficit ≤ 3 %, inflation ≤ 3 %, dette ≤ 70 % du PIB, pression fiscale ≥ 20 %.',
   'https://fr.wikipedia.org/wiki/Union_%C3%A9conomique_et_mon%C3%A9taire_ouest-africaine'),
 mk('Le revenu national disponible brut se distingue du PIB par…','La prise en compte des revenus et transferts avec le reste du monde','Le seul secteur agricole','L\'exclusion des impôts','Les stocks uniquement',
   'On passe du PIB au RNB en ajoutant les revenus nets reçus de l\'étranger (salaires, dividendes) puis les transferts courants nets.',
   'https://fr.wikipedia.org/wiki/Revenu_national_brut'),
 mk('La théorie quantitative de la monnaie (MV = PT) suggère qu\'à long terme…','L\'inflation est un phénomène monétaire','La monnaie est neutre sur les prix','Le chômage dépend de la monnaie','Les taux sont fixes',
   'Si la vitesse V et le volume T sont stables, une hausse de la masse monétaire M se traduit par une hausse des prix P (école monétariste, Friedman).',
   'https://fr.wikipedia.org/wiki/Th%C3%A9orie_quantitative_de_la_monnaie'),
 mk('Le déficit jumeau désigne la coexistence…','D\'un déficit budgétaire et d\'un déficit courant','De deux excédents','D\'inflation et déflation','De deux monnaies',
   'Un déficit public élevé peut se refléter dans un déficit extérieur, l\'épargne nationale ne finançant pas l\'investissement et la dépense publique.',
   'https://fr.wikipedia.org/wiki/D%C3%A9ficits_jumeaux'),
] .forEach(x => macro.push(x));
// Taux d'inflation IPC (paramétrique)
[[100,103,3],[100,102,2],[120,126,5],[150,153,2],[100,110,10],[200,204,2],[100,101,1],[130,143,10],[110,121,10],[100,104,4]]
.forEach(([i0, i1, tx]) => macro.push(mk(
  `L'indice des prix passe de ${i0} à ${i1} en un an. Le taux d'inflation est de :`,
  `${tx} %`, `${tx+2} %`, `${Math.round(tx/2)} %`, `${i1-i0} points fixes`,
  `Inflation = (${i1} − ${i0}) ÷ ${i0} = ${tx} %. L'UEMOA vise un taux inférieur ou égal à 3 %.`,
  'https://fr.wikipedia.org/wiki/Indice_des_prix_%C3%A0_la_consommation')));

// ---------------- COMMERCE, DÉVELOPPEMENT & AFRIQUE (+55 → 60) --------
const com = [];
[
 mk('La ZLECAf est…','La Zone de Libre-Échange Continentale Africaine','Une monnaie unique','Une banque centrale','Un port',
   'Entrée en vigueur en 2021, la ZLECAf vise le plus grand marché unique du monde en nombre de pays, réduisant droits de douane et barrières intra-africaines.',
   'https://fr.wikipedia.org/wiki/Zone_de_libre-%C3%A9change_continentale_africaine'),
 mk('L\'avantage comparatif (Ricardo) justifie que chaque pays…','Se spécialise dans les productions où il est relativement le plus efficace','Produise tout lui-même','Ferme ses frontières','Importe uniquement',
   'Même un pays désavantagé partout gagne à se spécialiser là où son désavantage est le plus faible : le commerce accroît le bien-être mutuel.',
   'https://fr.wikipedia.org/wiki/Avantage_comparatif'),
 mk('La CEDEAO regroupe…','15 États d\'Afrique de l\'Ouest','8 pays seulement','Toute l\'Afrique','Les pays du Maghreb',
   'La Communauté Économique des États de l\'Afrique de l\'Ouest (1975) vise l\'intégration économique et la libre circulation ; l\'UEMOA en est un sous-ensemble de 8 pays partageant le FCFA.',
   'https://fr.wikipedia.org/wiki/Communaut%C3%A9_%C3%A9conomique_des_%C3%89tats_de_l%27Afrique_de_l%27Ouest'),
 mk('Le protectionnisme consiste à…','Protéger la production nationale par des barrières aux importations','Ouvrir totalement les frontières','Supprimer la monnaie','Interdire l\'épargne',
   'Droits de douane, quotas, normes : le protectionnisme protège des secteurs mais renchérit les prix et peut susciter des représailles.',
   'https://fr.wikipedia.org/wiki/Protectionnisme'),
 mk('Les termes de l\'échange d\'un pays s\'améliorent quand…','Le prix de ses exportations augmente relativement à celui de ses importations','Ses importations coûtent plus cher','Sa monnaie s\'effondre','Ses exportations chutent',
   'Termes de l\'échange = indice prix export ÷ indice prix import ; leur dégradation pèse sur les pays exportateurs de matières premières.',
   'https://fr.wikipedia.org/wiki/Termes_de_l%27%C3%A9change'),
 mk('L\'OMC a pour mission principale…','De réguler et libéraliser le commerce international','D\'émettre la monnaie mondiale','De fixer les salaires','De financer les routes',
   'L\'Organisation Mondiale du Commerce (1995, succède au GATT) édicte les règles multilatérales et arbitre les différends commerciaux.',
   'https://fr.wikipedia.org/wiki/Organisation_mondiale_du_commerce'),
 mk('L\'indice de développement humain (IDH) combine…','Revenu, éducation et santé (espérance de vie)','Le PIB seul','La population et la superficie','Les exportations',
   'Créé par le PNUD (1990), l\'IDH varie de 0 à 1 et propose une mesure du développement plus large que le seul revenu par habitant.',
   'https://fr.wikipedia.org/wiki/Indice_de_d%C3%A9veloppement_humain'),
 mk('Le franc CFA (XOF) est partagé par…','Les 8 pays de l\'UEMOA','La seule Côte d\'Ivoire','Tous les pays africains','La CEDEAO entière',
   'Bénin, Burkina Faso, Côte d\'Ivoire, Guinée-Bissau, Mali, Niger, Sénégal et Togo utilisent le franc CFA ouest-africain émis par la BCEAO.',
   'https://fr.wikipedia.org/wiki/Franc_CFA'),
 mk('Le développement durable repose sur trois piliers :','Économique, social et environnemental','Militaire, culturel et sportif','Monétaire, fiscal et douanier','Public, privé et associatif',
   'Défini par le rapport Brundtland (1987) : répondre aux besoins présents sans compromettre ceux des générations futures.',
   'https://fr.wikipedia.org/wiki/D%C3%A9veloppement_durable'),
 mk('Les Objectifs de Développement Durable (ODD) de l\'ONU sont au nombre de…','17','8','5','30',
   'Adoptés en 2015 (Agenda 2030), les 17 ODD succèdent aux 8 Objectifs du Millénaire, couvrant pauvreté, faim, santé, éducation, climat, etc.',
   'https://fr.wikipedia.org/wiki/Objectifs_de_d%C3%A9veloppement_durable'),
 mk('Le libre-échange, selon ses partisans, favorise…','La spécialisation, la baisse des prix et la croissance','L\'autarcie','La désindustrialisation garantie','La disparition des échanges',
   'Il élargit les marchés et stimule la concurrence ; ses critiques soulignent les coûts d\'ajustement et les inégalités qu\'il peut aggraver.',
   'https://fr.wikipedia.org/wiki/Libre-%C3%A9change'),
 mk('La dépendance aux matières premières expose les économies africaines à…','La volatilité des cours mondiaux','Une stabilité parfaite','L\'absence de croissance monétaire','Un excédent garanti',
   'La concentration des exportations sur quelques produits (cacao, coton, pétrole) fragilise les recettes ; la diversification est un enjeu clé.',
   'https://fr.wikipedia.org/wiki/Mal%C3%A9diction_des_ressources_naturelles'),
 mk('L\'aide publique au développement (APD) désigne…','Les flux concessionnels des pays donneurs vers les pays en développement','Les investissements privés','Les envois de fonds des migrants','Les exportations de matières premières',
   'L\'APD (dons et prêts à conditions favorables) est suivie par l\'OCDE ; une cible historique de 0,7 % du RNB des donneurs est rarement atteinte.',
   'https://fr.wikipedia.org/wiki/Aide_publique_au_d%C3%A9veloppement'),
 mk('Les investissements directs étrangers (IDE) correspondent à…','Une prise de participation durable d\'un investisseur étranger dans une entreprise locale','Un prêt bancaire courant','Un don humanitaire','Une importation de biens',
   'Les IDE apportent capital, technologies et emplois ; ils sont recherchés mais posent des questions de souveraineté et de rapatriement des profits.',
   'https://fr.wikipedia.org/wiki/Investissement_direct_%C3%A0_l%27%C3%A9tranger'),
 mk('Le taux de pauvreté monétaire mesure…','La part de la population sous un seuil de revenu/consommation','Le nombre de millionnaires','Le PIB par habitant','L\'espérance de vie',
   'Le seuil peut être absolu (ex. 2,15 $ PPA/jour, Banque mondiale) ou relatif (fraction du revenu médian) ; il guide les politiques sociales.',
   'https://fr.wikipedia.org/wiki/Seuil_de_pauvret%C3%A9'),
] .forEach(x => com.push(x));
// Balance commerciale (paramétrique)
[[500,400,100],[300,450,-150],[800,650,150],[200,200,0],[1000,720,280],[600,900,-300],[450,300,150],[750,750,0],[900,640,260],[350,500,-150]]
.forEach(([x, m, s]) => com.push(mk(
  `Un pays exporte pour ${F(x)} et importe pour ${F(m)} milliards FCFA. Solde de la balance commerciale :`,
  `${s<0?'Déficit de '+F(-s):(s===0?'Équilibre (0)':'Excédent de '+F(s))} milliards`, `${s<0?'Excédent de '+F(-s):'Déficit de '+F(Math.abs(s)+50)} milliards`, `${F(x+m)} milliards`, `${F(Math.round(Math.abs(s)/2))} milliards`,
  `Solde = exportations − importations = ${F(x)} − ${F(m)} = ${F(s)} milliards ${s<0?'(déficit)':s===0?'(équilibre)':'(excédent)'}.`,
  'https://fr.wikipedia.org/wiki/Balance_commerciale')));

// ---------------- HISTOIRE DE LA PENSÉE ÉCONOMIQUE (+89 → 92) --------
const hpe = [];
[
 ['Adam Smith','La richesse des nations (1776) ; « main invisible » et division du travail','le père de l\'économie politique classique et du libéralisme'],
 ['David Ricardo','La théorie de l\'avantage comparatif et de la rente foncière','un classique défenseur du libre-échange'],
 ['Karl Marx','Le Capital ; théorie de la valeur-travail et de la plus-value','le fondateur du socialisme scientifique'],
 ['John Maynard Keynes','La Théorie générale (1936) ; rôle de la demande effective et de l\'État','le fondateur de la macroéconomie moderne'],
 ['Milton Friedman','Le monétarisme et la critique de l\'interventionnisme','le chef de file de l\'école de Chicago'],
 ['Thomas Malthus','La thèse d\'une population croissant plus vite que les subsistances','un classique pessimiste sur la démographie'],
 ['Léon Walras','La théorie de l\'équilibre général','un fondateur du marginalisme et de l\'école de Lausanne'],
 ['Joseph Schumpeter','La « destruction créatrice » et le rôle de l\'entrepreneur innovateur','le théoricien de l\'innovation'],
 ['Amartya Sen','L\'approche par les capabilités et l\'économie du développement','un Nobel proche de l\'économie du bien-être'],
 ['Jean-Baptiste Say','La « loi des débouchés » (l\'offre crée sa propre demande)','un économiste classique français'],
]
.forEach(([nom, oeuvre, role]) => hpe.push(mk(
  `À quel économiste associe-t-on ${oeuvre.charAt(0).toLowerCase()+oeuvre.slice(1)} ?`,
  nom, nom === 'Karl Marx' ? 'Adam Smith' : 'Karl Marx', nom === 'John Maynard Keynes' ? 'Milton Friedman' : 'John Maynard Keynes', nom === 'David Ricardo' ? 'Léon Walras' : 'David Ricardo',
  `${nom} est ${role} ; on lui doit ${oeuvre}.`,
  'https://fr.wikipedia.org/wiki/Histoire_de_la_pens%C3%A9e_%C3%A9conomique')));
[
 mk('Le courant physiocrate (Quesnay) considérait comme seule source de richesse…','L\'agriculture','Le commerce','L\'industrie','La finance',
   'Les physiocrates du XVIIIᵉ siècle (Tableau économique de Quesnay) voyaient dans la terre le « produit net » et prônaient le laissez-faire.',
   'https://fr.wikipedia.org/wiki/Physiocratie'),
 mk('Le mercantilisme prônait…','L\'accumulation de métaux précieux via un excédent commercial','Le libre-échange total','L\'abolition de l\'État','La décroissance',
   'Doctrine des XVIᵉ-XVIIIᵉ siècles : la puissance de l\'État passe par l\'or et l\'argent, d\'où le soutien aux exportations et la restriction des importations.',
   'https://fr.wikipedia.org/wiki/Mercantilisme'),
 mk('La « main invisible » d\'Adam Smith illustre…','La coordination spontanée des intérêts individuels par le marché','La planification centrale','La charité obligatoire','Le contrôle des prix',
   'En poursuivant son intérêt, chacun contribue involontairement au bien commun ; concept fondateur de la pensée libérale.',
   'https://fr.wikipedia.org/wiki/Main_invisible'),
 mk('Le marginalisme (années 1870) a introduit…','L\'analyse en termes d\'utilité et de coûts marginaux','La valeur-travail','La planification','Le mercantilisme',
   'Jevons, Menger et Walras fondent la valeur sur l\'utilité marginale (dernière unité consommée), rupture avec la valeur-travail classique.',
   'https://fr.wikipedia.org/wiki/Marginalisme'),
 mk('L\'école keynésienne recommande, en récession…','Une relance de la demande par la dépense publique','L\'austérité systématique','La seule baisse des salaires','L\'inaction',
   'Face au chômage involontaire, l\'État soutient la demande effective ; le multiplicateur amplifie l\'effet des dépenses publiques.',
   'https://fr.wikipedia.org/wiki/Keyn%C3%A9sianisme'),
 mk('Les néoclassiques supposent des agents…','Rationnels maximisant leur utilité/profit','Toujours altruistes','Irrationnels par nature','Indifférents aux prix',
   'L\'homo œconomicus optimise sous contrainte ; ce cadre est nuancé par l\'économie comportementale (Kahneman, Thaler).',
   'https://fr.wikipedia.org/wiki/%C3%89cole_n%C3%A9oclassique'),
 mk('L\'institutionnalisme (Veblen, North) insiste sur…','Le rôle des institutions et des règles dans l\'économie','Le seul équilibre des prix','La neutralité de l\'État','L\'absence d\'histoire',
   'Les institutions (droit, normes, organisations) structurent les incitations et expliquent les trajectoires de développement.',
   'https://fr.wikipedia.org/wiki/%C3%89conomie_institutionnelle'),
 mk('L\'économie du bien-être étudie…','L\'efficacité et l\'équité de l\'allocation des ressources','Uniquement la Bourse','La comptabilité des entreprises','La logistique',
   'Elle mobilise l\'optimum de Pareto et les fonctions de bien-être social pour évaluer les politiques publiques.',
   'https://fr.wikipedia.org/wiki/%C3%89conomie_du_bien-%C3%AAtre'),
 mk('La « destruction créatrice » de Schumpeter décrit…','Le remplacement des activités anciennes par l\'innovation','La destruction pure des richesses','Une crise financière','La déflation',
   'L\'innovation détruit des rentes et des emplois anciens tout en créant de nouvelles activités : moteur du capitalisme.',
   'https://fr.wikipedia.org/wiki/Destruction_cr%C3%A9atrice'),
 mk('L\'approche par les capabilités d\'Amartya Sen définit le développement comme…','L\'expansion des libertés réelles et des possibilités de choix des personnes','La seule hausse du PIB','L\'accumulation d\'or','La croissance démographique',
   'Le développement est un élargissement des « capabilités » (santé, éducation, participation), au-delà du revenu ; base de l\'IDH.',
   'https://fr.wikipedia.org/wiki/Capabilit%C3%A9'),
 mk('Le monétarisme de Friedman affirme que…','« L\'inflation est toujours et partout un phénomène monétaire »','Les dépenses publiques n\'ont aucun coût','La monnaie est sans effet','L\'État doit tout planifier',
   'Il préconise une croissance stable et prévisible de la masse monétaire plutôt qu\'un pilotage discrétionnaire.',
   'https://fr.wikipedia.org/wiki/Mon%C3%A9tarisme'),
 mk('La loi de Say énonce que…','L\'offre crée sa propre demande','La demande précède toujours l\'offre','L\'épargne est nuisible','Les crises sont permanentes',
   'Pour les classiques, toute production distribue des revenus permettant d\'écouler la production ; Keynes la conteste avec la demande effective.',
   'https://fr.wikipedia.org/wiki/Loi_de_Say'),
 mk('L\'économie comportementale (Kahneman, Thaler) montre que les décisions…','S\'écartent souvent de la rationalité pure (biais cognitifs)','Sont toujours optimales','Ignorent les émotions','Sont aléatoires',
   'Biais d\'ancrage, aversion aux pertes, comptabilité mentale : les « nudges » exploitent ces régularités pour orienter les choix.',
   'https://fr.wikipedia.org/wiki/%C3%89conomie_comportementale'),
 mk('Pour Malthus, sans frein, la population croît…','De façon géométrique alors que les subsistances croissent arithmétiquement','Moins vite que les ressources','À l\'infini sans conséquence','De façon stable',
   'Ce déséquilibre annoncerait famines et misère ; les gains de productivité agricole ont largement démenti ce pessimisme.',
   'https://fr.wikipedia.org/wiki/Pi%C3%A8ge_malthusien'),
 mk('Le libéralisme économique défend prioritairement…','La liberté des marchés et la limitation de l\'intervention de l\'État','La collectivisation','La planification centrale','Le protectionnisme généralisé',
   'De Smith à Hayek, il valorise la concurrence, la propriété privée et la coordination par les prix.',
   'https://fr.wikipedia.org/wiki/Lib%C3%A9ralisme_%C3%A9conomique'),
] .forEach(x => hpe.push(x));

module.exports = { micro, macro, com, hpe };
