// =====================================================================
// data_extra.js — packs additionnels v2.3
// Statistique & Économétrie (avancée) · Machine learning & Deep learning ·
// Suivi-évaluation de projets, programmes & politiques de développement
//
// Tous les packs ont des questions QCM avec ≥ 4 propositions :
//   choices: [a, b, c, d, ...] (4 ou plus)
//   correctIndices: [n] (1 bonne) ou [n1, n2, ...] (plusieurs bonnes)
//   r reste rempli pour la comparaison souple en mode texte libre
// =====================================================================

const STAT_NAME = 'Statistiques et économétrie';
const ML_NAME   = 'Machine learning et deep learning';
const SE_NAME   = 'Suivi-évaluation des projets et politiques';

// Helper : crée une question QCM
function q(id, qText, choices, correctIndices, r, e, ref, pts) {
  const ci = Array.isArray(correctIndices) ? correctIndices : [correctIndices];
  return { id, q: qText, choices, correctIndices: ci, r, e, ref, pts: pts || 1 };
}

// ---------------------------------------------------------------------
// MANCHE 1 — séries de 4 questions à 1 pt (40 s pour les 4)
// ---------------------------------------------------------------------
const m1Packs = [
  // ============ STATISTIQUE / ÉCONOMÉTRIE AVANCÉE =====================
  {
    titre: 'Modèles linéaires avancés (1)',
    theme: 'Économétrie',
    domain: STAT_NAME,
    questions: [
      q('q1', 'Quel critère pénalise la complexité d\'un modèle par 2k − 2 ln L où k = nombre de paramètres ?',
        ['AIC', 'BIC', 'R² ajusté', 'Mallows Cp'], [0],
        'AIC',
        'Akaike Information Criterion : équilibre vraisemblance et parcimonie.',
        'Akaike, 1974.'),
      q('q2', 'Quel critère pénalise plus fortement que l\'AIC avec un terme k·ln(n) ?',
        ['BIC (Schwarz)', 'AIC corrigé', 'F-statistique', 'Durbin-Watson'], [0],
        'BIC (Schwarz)',
        'BIC = k·ln(n) − 2·ln L : plus sévère sur la complexité, favorise les modèles parcimonieux.',
        'Schwarz, 1978.'),
      q('q3', 'Quelle statistique teste l\'autocorrélation d\'ordre 1 des résidus en MCO ?',
        ['Durbin-Watson', 'Breusch-Pagan', 'Jarque-Bera', 'White'], [0],
        'Durbin-Watson',
        'DW ≈ 2 indique pas d\'autocorrélation ; < 2 = positive ; > 2 = négative.',
        'Durbin & Watson, 1950.'),
      q('q4', 'Quel test détecte l\'hétéroscédasticité des résidus ?',
        ['Breusch-Pagan', 'Dickey-Fuller', 'Durbin-Watson', 'Wald'], [0],
        'Breusch-Pagan',
        'Régresse les résidus² sur les variables explicatives ; test du multiplicateur de Lagrange.',
        'Breusch & Pagan, 1979.')
    ]
  },
  {
    titre: 'Séries temporelles (1)',
    theme: 'Économétrie des séries',
    domain: STAT_NAME,
    questions: [
      q('q1', 'Quel test vérifie la présence d\'une racine unitaire (non-stationnarité) ?',
        ['ADF (Dickey-Fuller augmenté)', 'Jarque-Bera', 'Hausman', 'White'], [0],
        'ADF (Dickey-Fuller augmenté)',
        'H0 : présence de racine unitaire → série non stationnaire.',
        'Dickey & Fuller, 1979.'),
      q('q2', 'Quel modèle combine AR, intégration (différenciation) et MA ?',
        ['ARIMA', 'GARCH', 'VAR', 'VECM'], [0],
        'ARIMA',
        'AutoRegressive Integrated Moving Average ; notation ARIMA(p,d,q).',
        'Box & Jenkins, 1976.'),
      q('q3', 'Quel modèle décrit la volatilité conditionnelle (variance changeante) ?',
        ['GARCH', 'ARIMA', 'VAR', 'OLS'], [0],
        'GARCH',
        'Generalized Autoregressive Conditional Heteroskedasticity ; Bollerslev 1986.',
        'Bollerslev, 1986.'),
      q('q4', 'Le test de Johansen sert à détecter…',
        ['Le rang de cointégration entre plusieurs séries', 'L\'autocorrélation', 'L\'hétéroscédasticité', 'La normalité'], [0],
        'Le rang de cointégration',
        'Test du rapport de vraisemblance ; identifie le nombre de vecteurs de cointégration dans un VAR.',
        'Johansen, 1991.')
    ]
  },
  {
    titre: 'Modèles non-linéaires',
    theme: 'Économétrie qualitative',
    domain: STAT_NAME,
    questions: [
      q('q1', 'Le modèle logit utilise quelle fonction de lien ?',
        ['Fonction logistique', 'Fonction probit (Φ)', 'Fonction identité', 'Tangente hyperbolique'], [0],
        'Fonction logistique',
        'P(Y=1|X) = 1/(1+e^(-Xβ)) ; log-odds linéaire en X.',
        'Berkson, 1944.'),
      q('q2', 'Le modèle probit utilise quelle fonction de lien ?',
        ['Fonction de répartition normale standard Φ', 'Logistique', 'Exponentielle', 'Logarithmique'], [0],
        'Φ (loi normale standard)',
        'P(Y=1|X) = Φ(Xβ) ; résultats proches du logit mais coefficients non-équivalents.',
        'Bliss, 1934.'),
      q('q3', 'Quel modèle pour variable dépendante de comptage (Y ∈ N) ?',
        ['Poisson', 'Probit', 'Tobit', 'OLS'], [0],
        'Modèle de Poisson',
        'log(λ) = Xβ ; suppose E(Y) = Var(Y), sinon utiliser binomial négatif.',
        'Cameron & Trivedi, 1998.'),
      q('q4', 'Le modèle Tobit est utilisé quand la variable dépendante est…',
        ['Censurée (tronquée à 0 ou autre seuil)', 'Discrète binaire', 'De comptage', 'Catégorielle multinomiale'], [0],
        'Censurée',
        'Modélise une variable latente Y* dont seule la valeur tronquée est observée.',
        'Tobin, 1958.')
    ]
  },
  {
    titre: 'Données de panel',
    theme: 'Économétrie panel',
    domain: STAT_NAME,
    questions: [
      q('q1', 'Quel modèle de panel suppose que l\'effet individuel αi est corrélé avec les régresseurs X ?',
        ['Effets fixes (within)', 'Effets aléatoires (RE)', 'Between', 'Pooled OLS'], [0],
        'Effets fixes',
        'Within estimator : élimine les effets individuels en différenciant ; biais réduit si α_i corrélé à X.',
        'Wooldridge, Econometric Analysis of Cross Section and Panel Data.'),
      q('q2', 'Quel test arbitre entre effets fixes et effets aléatoires ?',
        ['Hausman', 'White', 'Jarque-Bera', 'Sargan'], [0],
        'Test de Hausman',
        'H0 : RE est cohérent et efficace. Rejet → préférer effets fixes.',
        'Hausman, 1978.'),
      q('q3', 'Le GMM en panel dynamique (Arellano-Bond) sert à…',
        ['Instrumenter les retards endogènes Y(t-1)', 'Tester la stationnarité', 'Calculer les résidus', 'Estimer les effets quadratiques'], [0],
        'Instrumenter Y(t-1)',
        'Arellano-Bond 1991 : différencie, puis instrumente avec les niveaux retardés.',
        'Arellano & Bond, 1991.'),
      q('q4', 'Quel test de Sargan vérifie en GMM ?',
        ['La validité des instruments (sur-identification)', 'L\'autocorrélation', 'La stationnarité', 'L\'hétéroscédasticité'], [0],
        'Validité des instruments',
        'Test de sur-identification : H0 = instruments tous valides.',
        'Sargan, 1958 ; Hansen J, 1982.')
    ]
  },
  {
    titre: 'Métriques d\'évaluation',
    theme: 'Statistique appliquée',
    domain: STAT_NAME,
    questions: [
      q('q1', 'Quel coefficient mesure la qualité d\'ajustement d\'une régression OLS ?',
        ['R² (coefficient de détermination)', 'AIC', 'F-statistique', 'Durbin-Watson'], [0],
        'R²',
        'R² = 1 − SCR/SCT ; entre 0 et 1.',
        'Wright, 1921.'),
      q('q2', 'Le RMSE est la racine carrée de…',
        ['L\'erreur quadratique moyenne (MSE)', 'L\'erreur absolue moyenne', 'La somme des erreurs', 'La variance des prédictions'], [0],
        'MSE',
        'Root Mean Squared Error : sensible aux outliers, exprime l\'erreur dans l\'unité de la variable cible.',
        'Hyndman & Athanasopoulos, Forecasting.'),
      q('q3', 'La métrique MAPE exprime…',
        ['Erreur absolue moyenne en pourcentage', 'Erreur quadratique moyenne', 'Variance résiduelle', 'Information de Fisher'], [0],
        'MAPE',
        'Mean Absolute Percentage Error : (1/n)·Σ|y−ŷ|/|y| × 100 %.',
        'Hyndman & Koehler, 2006.'),
      q('q4', 'Le R² peut être négatif dans quelles conditions ?',
        ['En régression hors échantillon (test set) ou sans constante quand le modèle est pire que la moyenne', 'Jamais', 'Uniquement en régression non-linéaire', 'Quand n < k'], [0],
        'En hors-échantillon ou sans constante',
        'En train OLS avec constante R² ∈ [0,1] ; sur test set ou sans intercept R² peut être < 0.',
        'James, Witten, Hastie, Tibshirani, ISLR.')
    ]
  },

  // =================== MACHINE LEARNING / DEEP LEARNING ================
  {
    titre: 'Fondamentaux ML (1)',
    theme: 'Apprentissage supervisé',
    domain: ML_NAME,
    questions: [
      q('q1', 'Quel algorithme classe un point selon les k voisins les plus proches ?',
        ['k-NN (k-Nearest Neighbors)', 'k-means', 'SVM', 'Random Forest'], [0],
        'k-NN',
        'Classification : vote majoritaire des k plus proches voisins dans l\'espace des features.',
        'Cover & Hart, 1967.'),
      q('q2', 'Quel algorithme cherche l\'hyperplan séparateur de marge maximale ?',
        ['SVM (Support Vector Machine)', 'k-NN', 'Régression linéaire', 'Naive Bayes'], [0],
        'SVM',
        'Maximisation de la marge entre les classes ; kernels (RBF, polynomial) pour le non-linéaire.',
        'Vapnik, 1995.'),
      q('q3', 'Random Forest combine plusieurs…',
        ['Arbres de décision avec bagging + bootstrap des features', 'Réseaux de neurones', 'Régressions logistiques', 'SVM'], [0],
        'Arbres de décision (bagging)',
        'Bagging : bootstrap des échantillons + sélection aléatoire des features ; réduit la variance.',
        'Breiman, 2001.'),
      q('q4', 'Le gradient boosting construit les arbres…',
        ['Séquentiellement, chaque arbre corrigeant les erreurs du précédent', 'En parallèle indépendamment', 'Par bagging', 'Par sélection aléatoire'], [0],
        'Séquentiellement',
        'Chaque nouvel arbre apprend les résidus pondérés. XGBoost, LightGBM, CatBoost.',
        'Friedman, 2001.')
    ]
  },
  {
    titre: 'Réseaux de neurones',
    theme: 'Deep learning',
    domain: ML_NAME,
    questions: [
      q('q1', 'Quelle fonction d\'activation produit des sorties dans [0,1] et est sujette au vanishing gradient ?',
        ['Sigmoïde', 'ReLU', 'Tanh', 'Softmax'], [0],
        'Sigmoïde',
        'σ(x) = 1/(1+e^(-x)) ; saturation pour |x| grand → gradient ≈ 0.',
        'Goodfellow et al., Deep Learning, 2016.'),
      q('q2', 'Quelle fonction d\'activation vaut max(0, x) et accélère l\'entraînement ?',
        ['ReLU', 'Sigmoïde', 'Tanh', 'Linéaire'], [0],
        'ReLU',
        'Rectified Linear Unit : pas de saturation pour x > 0 ; problème dying ReLU pour x < 0.',
        'Nair & Hinton, 2010.'),
      q('q3', 'Le dropout pendant l\'entraînement consiste à…',
        ['Désactiver aléatoirement une fraction des neurones', 'Augmenter la taille du batch', 'Réduire le learning rate', 'Ajouter du bruit aux poids'], [0],
        'Désactiver des neurones aléatoirement',
        'Réduit l\'overfitting en empêchant la co-adaptation des neurones.',
        'Srivastava et al., 2014.'),
      q('q4', 'La batch normalisation normalise…',
        ['Les activations à chaque couche (moyenne 0, variance 1)', 'Les poids initiaux', 'Les gradients en fin de backprop', 'Les biais des sorties'], [0],
        'Les activations',
        'Stabilise et accélère l\'entraînement ; introduit β, γ apprenables.',
        'Ioffe & Szegedy, 2015.')
    ]
  },
  {
    titre: 'Architectures spécialisées',
    theme: 'Deep learning',
    domain: ML_NAME,
    questions: [
      q('q1', 'Quel type de réseau est conçu pour les images via convolutions ?',
        ['CNN (Convolutional Neural Network)', 'RNN', 'Transformer', 'MLP'], [0],
        'CNN',
        'Filtres convolutifs + pooling ; partage de poids, invariance à la translation.',
        'LeCun et al., 1989.'),
      q('q2', 'Quel type de réseau gère naturellement les séquences avec état caché ?',
        ['RNN (Recurrent Neural Network)', 'CNN', 'MLP', 'Autoencoder'], [0],
        'RNN',
        'Récurrence h_t = f(h_{t-1}, x_t) ; sujet au vanishing gradient → LSTM/GRU.',
        'Elman, 1990.'),
      q('q3', 'L\'architecture Transformer repose principalement sur…',
        ['Le mécanisme d\'attention (self-attention)', 'Les convolutions 3D', 'Les états récurrents', 'Le pooling spatial'], [0],
        'Self-attention',
        'Attention multi-tête, pas de récurrence ; base de BERT, GPT, T5.',
        'Vaswani et al., "Attention Is All You Need", 2017.'),
      q('q4', 'Un autoencoder apprend à…',
        ['Reconstruire son entrée via un goulot d\'étranglement', 'Classer des images', 'Générer du texte', 'Maximiser la marge'], [0],
        'Reconstruire l\'entrée',
        'Encoder → représentation latente → decoder ; usage pour réduction de dimension, débruitage, anomalie.',
        'Hinton & Salakhutdinov, 2006.')
    ]
  },
  {
    titre: 'Évaluation et applications ML',
    theme: 'Évaluation modèles',
    domain: ML_NAME,
    questions: [
      q('q1', 'Quelle métrique vaut TP / (TP+FP) en classification binaire ?',
        ['Précision (precision)', 'Rappel (recall)', 'F1-score', 'Accuracy'], [0],
        'Précision',
        'Proportion de prédictions positives qui sont correctes ; complémentaire au recall.',
        'Manning et al., Information Retrieval, 2008.'),
      q('q2', 'Quelle métrique vaut TP / (TP+FN) ?',
        ['Rappel (recall, sensibilité)', 'Précision', 'Spécificité', 'F1-score'], [0],
        'Rappel',
        'Proportion de positifs réels correctement détectés. Crucial en médical et fraude.',
        'Manning et al., 2008.'),
      q('q3', 'Le F1-score est…',
        ['La moyenne harmonique de précision et rappel', 'La moyenne arithmétique', 'Le produit P × R', 'L\'écart-type des deux'], [0],
        'Moyenne harmonique de P et R',
        'F1 = 2·P·R/(P+R) ; pénalise les déséquilibres entre P et R.',
        'Van Rijsbergen, 1979.'),
      q('q4', 'L\'AUC-ROC mesure…',
        ['L\'aire sous la courbe ROC (TPR vs FPR)', 'La somme des résidus', 'L\'erreur quadratique', 'L\'entropie croisée'], [0],
        'Aire sous courbe ROC',
        'AUC ∈ [0,1] ; 0.5 = aléatoire, 1 = parfait. Insensible au seuil de décision.',
        'Hanley & McNeil, 1982.')
    ]
  },

  // =============== SUIVI-ÉVALUATION DES PROJETS / POLITIQUES ===========
  {
    titre: 'Cadre logique et GAR',
    theme: 'Planification de projet',
    domain: SE_NAME,
    questions: [
      q('q1', 'Quels sont les 4 niveaux du cadre logique (logframe) ?',
        ['Activités → Produits → Effets → Impact', 'Inputs → Outputs → Outcomes → Goals', 'Buts → Stratégies → Tactiques → Actions', 'Plan → Do → Check → Act'], [0, 1],
        'Activités → Produits → Effets → Impact',
        'Hiérarchie des résultats : Activités/Inputs, Produits (outputs), Effets (outcomes), Impact. Les deux formulations équivalentes sont acceptées.',
        'Banque mondiale, manuel GAR ; USAID logframe.'),
      q('q2', 'L\'approche GAR signifie…',
        ['Gestion Axée sur les Résultats', 'Gestion Agile et Rapide', 'Garantie d\'Aide au Recouvrement', 'Groupe d\'Analyse des Risques'], [0],
        'Gestion Axée sur les Résultats',
        'Results-Based Management (RBM) : focus sur les résultats à atteindre, mesurés par des indicateurs.',
        'PNUD Handbook on Planning, Monitoring and Evaluating for Development Results, 2009.'),
      q('q3', 'Que signifie l\'acronyme SMART pour les indicateurs ?',
        ['Spécifique, Mesurable, Atteignable, Réaliste, Temporel', 'Stratégique, Multidimensionnel, Axé, Réfléchi, Tangible', 'Solide, Mesurable, Adaptable, Réaliste, Total', 'Système de Mesure, d\'Analyse et de Reporting Total'], [0],
        'Spécifique, Mesurable, Atteignable, Réaliste, Temporel',
        'Critères classiques de qualité d\'un indicateur de performance.',
        'Doran, 1981 ; repris par tous les bailleurs.'),
      q('q4', 'La théorie du changement diffère du cadre logique car elle…',
        ['Explicite les hypothèses causales et les liens entre niveaux', 'Ne mentionne pas les indicateurs', 'Est un outil financier', 'Remplace les Termes de Référence'], [0],
        'Explicite les hypothèses causales',
        'TdC : description narrative + diagramme des liens causaux et hypothèses sous-jacentes.',
        'Weiss, 1995 ; CARE International ToC Guide.')
    ]
  },
  {
    titre: 'Critères du CAD/OCDE',
    theme: 'Évaluation de projets',
    domain: SE_NAME,
    questions: [
      q('q1', 'Combien de critères d\'évaluation le CAD/OCDE a-t-il définis (révision 2019) ?',
        ['6 (pertinence, cohérence, efficacité, efficience, impact, durabilité)', '5 (originaux : pertinence, efficacité, efficience, impact, durabilité)', '4', '7'], [0],
        '6 critères',
        'Mise à jour 2019 ajoute la "cohérence" aux 5 critères historiques.',
        'OECD/DAC, "Better Criteria for Better Evaluation", 2019.'),
      q('q2', 'Le critère "efficience" mesure…',
        ['Le rapport entre ressources et résultats obtenus', 'L\'atteinte des objectifs', 'La pertinence par rapport aux besoins', 'La durabilité dans le temps'], [0],
        'Ressources vs résultats',
        'Efficiency : économie des moyens pour produire les résultats ; rapport coût-efficacité.',
        'OECD/DAC, 2019.'),
      q('q3', 'Le critère "impact" évalue…',
        ['Les effets positifs et négatifs, directs et indirects, voulus ou non', 'Uniquement les effets prévus', 'Les coûts du projet', 'La satisfaction des bailleurs'], [0],
        'Effets directs/indirects, voulus/non voulus',
        'Impact = changements de long terme attribuables (au moins en partie) à l\'intervention.',
        'OECD/DAC, 2019.'),
      q('q4', 'Le critère "durabilité" examine…',
        ['Si les bénéfices se poursuivent après la fin de l\'intervention', 'Le respect de l\'environnement uniquement', 'Le calendrier du projet', 'La diversité des parties prenantes'], [0],
        'Continuité des bénéfices',
        'Sustainability : persistance des effets après la fin du financement ; appropriation locale.',
        'OECD/DAC, 2019.')
    ]
  },
  {
    titre: 'Bailleurs et outils de S&É',
    theme: 'Acteurs du développement',
    domain: SE_NAME,
    questions: [
      q('q1', 'Que signifie SYGRI au FIDA ?',
        ['Système de Gestion des Résultats et de l\'Impact', 'Système Général de Recensement Intégré', 'Stratégie de Gestion des Risques d\'Investissement', 'Sécurisation des Garanties pour les Routes d\'Investissement'], [0],
        'Système de Gestion des Résultats et de l\'Impact',
        'Outil du FIDA pour mesurer et rapporter les résultats des projets (indicateurs standards par catégorie).',
        'IFAD, RIMS / SYGRI handbook.'),
      q('q2', 'Le PNUD utilise principalement quel manuel pour le S&É ?',
        ['Handbook on Planning, Monitoring and Evaluating for Development Results', 'World Development Report', 'Africa Competitiveness Report', 'Human Development Report'], [0],
        'PNUD Handbook on PMERR',
        '« HPMEDR » : référence méthodologique principale du PNUD depuis 2009.',
        'UNDP, 2009.'),
      q('q3', 'La Banque mondiale utilise les ICRR pour…',
        ['Rapports de fin d\'exécution et résultats (Implementation Completion and Results Reports)', 'Indicateurs Composites de Risques Régionaux', 'Investissements Conjoints en Recherche', 'Inventaire des Crédits Régionaux'], [0],
        'Implementation Completion and Results Reports',
        'Document de clôture systématique pour tous les projets WB ; revu par l\'IEG.',
        'World Bank, Operations Manual.'),
      q('q4', 'Quel cadre standard de l\'ONU oriente les objectifs des projets de développement depuis 2015 ?',
        ['Les 17 Objectifs de Développement Durable (ODD)', 'Les Objectifs du Millénaire (OMD)', 'L\'Agenda 21', 'Le Cadre de Sendai'], [0],
        'Les 17 ODD',
        'Agenda 2030 : succède aux OMD ; 17 objectifs, 169 cibles, 232 indicateurs.',
        'ONU, Agenda 2030, 2015.')
    ]
  },
  {
    titre: 'Méthodes d\'évaluation d\'impact',
    theme: 'Évaluation d\'impact',
    domain: SE_NAME,
    questions: [
      q('q1', 'Quelle est la méthode "gold standard" en évaluation d\'impact ?',
        ['L\'essai contrôlé randomisé (RCT)', 'L\'étude de cas', 'L\'enquête de satisfaction', 'L\'analyse coût-bénéfice'], [0],
        'RCT (Randomized Controlled Trial)',
        'Assignation aléatoire au traitement → contre-factuel crédible. Banerjee, Duflo, Kremer (Nobel 2019).',
        'J-PAL, World Bank IE Toolkit.'),
      q('q2', 'La méthode des doubles différences (DID) requiert…',
        ['Une mesure avant/après pour traités ET témoins (hypothèse de tendances parallèles)', 'Une assignation aléatoire', 'Une discontinuité au seuil', 'Des variables instrumentales'], [0],
        'Avant/après × traités/témoins',
        'Difference-in-Differences : isole l\'effet du traitement en supposant tendances parallèles.',
        'Card & Krueger, 1994 ; Angrist & Pischke, Mostly Harmless Econometrics.'),
      q('q3', 'L\'appariement par score de propension (PSM) sert à…',
        ['Construire un groupe témoin comparable sur covariables observables', 'Détecter l\'autocorrélation', 'Estimer un VAR', 'Maximiser la vraisemblance'], [0],
        'Construire un groupe témoin comparable',
        'Rosenbaum & Rubin 1983 : matching sur le score = P(Traité=1|X).',
        'Rosenbaum & Rubin, 1983.'),
      q('q4', 'La régression sur discontinuité (RDD) exploite…',
        ['Un seuil arbitraire qui détermine l\'éligibilité au traitement', 'Une variable instrumentale', 'Une randomisation', 'Un placebo'], [0],
        'Un seuil d\'éligibilité',
        'Compare les unités juste au-dessus / juste en-dessous du cutoff ; quasi-RCT local.',
        'Thistlethwaite & Campbell, 1960 ; Hahn et al., 2001.')
    ]
  }
];

// ---------------------------------------------------------------------
// MANCHE 2 — duels de 6 questions (1 à 6 pts), 25 s par question
// ---------------------------------------------------------------------
const m2Packs = [
  // Statistique avancée — duel
  {
    titre: 'Économétrie avancée — duel',
    theme: 'Économétrie',
    domain: STAT_NAME,
    questions: [
      q('q1', 'Quelle méthode estime des paramètres en minimisant la somme des carrés des résidus ?',
        ['MCO (OLS)', 'MV (vraisemblance maximale)', 'GMM', 'GLS'], [0],
        'MCO',
        'Moindres Carrés Ordinaires ; β̂ = (X\'X)⁻¹X\'y.',
        'Gauss, 1809 ; Legendre, 1805.', 1),
      q('q2', 'La MCG (GLS) est préférable à la MCO quand…',
        ['Les résidus sont hétéroscédastiques ou autocorrélés', 'Les régresseurs sont colinéaires', 'L\'échantillon est petit', 'La variable dépendante est binaire'], [0],
        'Hétéroscédasticité ou autocorrélation',
        'Generalized Least Squares pondère selon la matrice de covariance Ω des erreurs.',
        'Aitken, 1935.', 2),
      q('q3', 'Une variable instrumentale doit satisfaire deux conditions :',
        ['Pertinence (cov(Z,X)≠0) et exogénéité (cov(Z,ε)=0)', 'Stationnarité et ergodicité', 'Normalité et indépendance', 'Linéarité et exclusion'], [0],
        'Pertinence + exogénéité',
        'Z corrélé à X (force) mais non corrélé à ε (validité). Tests : F faible si pertinence douteuse.',
        'Wooldridge, 2010.', 3),
      q('q4', 'Le test de spécification de Ramsey (RESET) vérifie…',
        ['Si la forme fonctionnelle est correctement spécifiée', 'L\'hétéroscédasticité', 'La normalité', 'La cointégration'], [0],
        'Forme fonctionnelle',
        'Ajoute des puissances de ŷ aux régresseurs ; significatives → modèle mal spécifié.',
        'Ramsey, 1969.', 4),
      q('q5', 'La méthode de Heckman corrige…',
        ['Le biais de sélection (échantillonnage non-aléatoire)', 'L\'autocorrélation', 'L\'hétéroscédasticité', 'La multicolinéarité'], [0],
        'Biais de sélection',
        'Procédure en 2 étapes : probit de sélection + insertion du ratio inverse de Mills.',
        'Heckman, 1979 (Nobel 2000).', 5),
      q('q6', 'Le test J de Hansen en GMM teste…',
        ['La validité des restrictions de sur-identification', 'La présence d\'autocorrélation d\'ordre 2', 'La normalité des résidus', 'L\'hétéroscédasticité'], [0],
        'Sur-identification (validité des instruments)',
        'Variante du test de Sargan robuste à l\'hétéroscédasticité ; H0 = instruments valides.',
        'Hansen, 1982.', 6)
    ]
  },
  // ML — duel
  {
    titre: 'Apprentissage et applications — duel',
    theme: 'Machine learning',
    domain: ML_NAME,
    questions: [
      q('q1', 'Que cherche à minimiser une fonction de perte en classification binaire avec sortie probabiliste ?',
        ['L\'entropie croisée binaire (log-loss)', 'L\'erreur quadratique moyenne', 'L\'erreur absolue moyenne', 'La distance de Manhattan'], [0],
        'Entropie croisée binaire',
        'L = −[y log(p) + (1−y) log(1−p)] ; pénalise fortement les prédictions confiantes mais fausses.',
        'Goodfellow et al., 2016.', 1),
      q('q2', 'En clustering, quel algorithme partitionne les données en k groupes en minimisant l\'inertie intra-classe ?',
        ['k-means', 'DBSCAN', 'Random Forest', 'PCA'], [0],
        'k-means',
        'Itère : (1) affectation au centroïde le plus proche, (2) mise à jour des centroïdes.',
        'MacQueen, 1967 ; Lloyd, 1982.', 2),
      q('q3', 'L\'analyse en composantes principales (PCA) cherche à…',
        ['Projeter les données sur les axes de variance maximale', 'Classer des données', 'Estimer une densité', 'Trouver des règles d\'association'], [0],
        'Maximiser la variance projetée',
        'Décomposition en valeurs propres de la matrice de covariance ; axes orthogonaux décorrélés.',
        'Pearson, 1901 ; Hotelling, 1933.', 3),
      q('q4', 'En deep learning, quel optimiseur adapte le learning rate par paramètre avec moments ?',
        ['Adam', 'SGD vanille', 'L-BFGS', 'Newton-Raphson'], [0],
        'Adam',
        'Adaptive Moment Estimation : moments d\'ordre 1 et 2 ; corrige le biais initial.',
        'Kingma & Ba, 2014.', 4),
      q('q5', 'Le fine-tuning d\'un modèle pré-entraîné (transfer learning) consiste à…',
        ['Réutiliser ses poids et ré-entraîner certaines couches sur une nouvelle tâche', 'Réduire le nombre de paramètres', 'Augmenter les données par bruit', 'Forcer la convergence'], [0],
        'Ré-entraîner certaines couches',
        'Économise du temps et des données ; particulièrement efficace pour CV (ImageNet) et NLP (BERT, GPT).',
        'Yosinski et al., 2014.', 5),
      q('q6', 'Le mécanisme d\'attention multi-tête (multi-head attention) permet…',
        ['De capturer plusieurs types de relations en parallèle dans différents sous-espaces', 'D\'accélérer l\'entraînement par gradient', 'De normaliser les couches', 'D\'éviter le surapprentissage uniquement'], [0],
        'Plusieurs types de relations en parallèle',
        'Chaque tête apprend une attention différente ; concaténées puis projetées.',
        'Vaswani et al., 2017.', 6)
    ]
  },
  // S&E projets — duel
  {
    titre: 'Suivi-évaluation — duel',
    theme: 'Suivi et évaluation',
    domain: SE_NAME,
    questions: [
      q('q1', 'Quelle est la principale différence entre suivi et évaluation ?',
        ['Le suivi est continu et opérationnel, l\'évaluation est ponctuelle et analytique', 'Le suivi est qualitatif, l\'évaluation est quantitative', 'Le suivi est externe, l\'évaluation est interne', 'Aucune différence'], [0],
        'Suivi = continu, évaluation = ponctuelle',
        'Monitoring suit l\'avancement (outputs, activités) ; évaluation analyse pertinence, impact, etc.',
        'OECD/DAC Glossary 2002.', 1),
      q('q2', 'La baseline (situation de référence) doit être collectée…',
        ['Avant le démarrage du projet (T0)', 'Au milieu du projet', 'À la fin', 'Une fois par an'], [0],
        'Avant le démarrage',
        'Permet la comparaison avant/après et le calcul des progrès.',
        'World Bank IE Handbook ; PNUD HPMEDR.', 2),
      q('q3', 'L\'attribution diffère de la contribution car elle…',
        ['Établit un lien causal exclusif, alors que la contribution reconnaît plusieurs facteurs', 'Concerne les coûts', 'Concerne le calendrier', 'Concerne les bénéficiaires'], [0],
        'Lien causal exclusif vs plusieurs facteurs',
        'Attribution = "le résultat est dû au projet" ; contribution = "le projet est l\'un des facteurs".',
        'Mayne, "Contribution Analysis", 2008.', 3),
      q('q4', 'La méthode Outcome Mapping du CRDI/IDRC se concentre sur…',
        ['Les changements de comportement des partenaires limitrophes', 'Les coûts d\'opportunité', 'Les indicateurs SMART', 'Les budgets'], [0],
        'Changements de comportement des partenaires limitrophes',
        'Earl, Carden & Smutylo 2001 ; alternative au logframe pour projets complexes.',
        'IDRC, Outcome Mapping, 2001.', 4),
      q('q5', 'Le critère "additionnalité" en évaluation financière mesure…',
        ['L\'effet incrémental d\'un financement par rapport au contre-factuel sans financement', 'Le coût total du projet', 'Le nombre de bénéficiaires supplémentaires', 'Le rendement annuel'], [0],
        'Effet incrémental vs contre-factuel',
        'Concept clé pour les banques de développement (BEI, IFC) ; justifie l\'intervention publique.',
        'BEI, Additionality Framework.', 5),
      q('q6', 'L\'évaluation réaliste (realist evaluation) cherche à expliquer…',
        ['"Ce qui marche, pour qui, dans quelles circonstances et pourquoi" via mécanismes-contexte-résultats', 'Le ROI financier', 'L\'efficience pure', 'Les indicateurs SMART'], [0],
        'Mécanismes-Contexte-Résultats (MCR)',
        'Pawson & Tilley 1997 ; alternative aux RCT pour les programmes complexes.',
        'Pawson & Tilley, Realistic Evaluation, 1997.', 6)
    ]
  }
];

// ---------------------------------------------------------------------
// MANCHE 3 — finales jusqu'à 9 points (15 s par question)
// ---------------------------------------------------------------------
const m3Packs = [
  {
    titre: 'Finale Statistique & Économétrie avancée',
    theme: 'Économétrie',
    domain: STAT_NAME,
    questions: [
      q('q1', 'Quel est le test usuel de normalité des résidus en économétrie ?',
        ['Jarque-Bera', 'Durbin-Watson', 'White', 'Hausman'], [0],
        'Jarque-Bera',
        'Combine skewness et kurtosis ; distribution χ² à 2 ddl sous H0.',
        'Jarque & Bera, 1980.'),
      q('q2', 'Quel test détecte la multicolinéarité ?',
        ['VIF (Variance Inflation Factor)', 'Hausman', 'ADF', 'KPSS'], [0],
        'VIF',
        'VIF > 5 ou 10 signale une multicolinéarité élevée.',
        'Belsley, Kuh & Welsch, 1980.'),
      q('q3', 'Que signifie ARIMA(p,d,q) ?',
        ['p AR, d différenciations, q MA', 'p paramètres, d retards, q quantiles', 'puissance, dimension, qualité', 'persistance, drift, quasi-stationnarité'], [0],
        'p AR, d intégrations, q MA',
        'AR(p) + différenciation d fois + MA(q).',
        'Box & Jenkins, 1976.'),
      q('q4', 'KPSS teste H0 = stationnarité, contrairement à ADF qui teste H0 = non-stationnarité. Vrai ou faux ?',
        ['Vrai', 'Faux', 'KPSS et ADF testent la même chose', 'Aucun ne teste la stationnarité'], [0],
        'Vrai',
        'KPSS (Kwiatkowski, Phillips, Schmidt, Shin, 1992) est complémentaire à ADF.',
        'KPSS, 1992.'),
      q('q5', 'Le test de Granger sert à détecter…',
        ['Une relation de causalité (au sens prédictif) entre deux séries', 'L\'autocorrélation', 'L\'hétéroscédasticité', 'La non-linéarité'], [0],
        'Causalité de Granger',
        'X cause Y si les valeurs passées de X améliorent la prédiction de Y.',
        'Granger, 1969 (Nobel 2003).'),
      q('q6', 'Que vise la régularisation L2 (ridge) en régression ?',
        ['Réduire les coefficients en pénalisant Σβ²', 'Annuler certains coefficients', 'Maximiser R²', 'Tester la normalité'], [0],
        'Pénalisation Σβ²',
        'Stabilise les coefficients en cas de multicolinéarité ; ne fait pas de sélection (≠ Lasso L1).',
        'Hoerl & Kennard, 1970.'),
      q('q7', 'Le Lasso (L1) effectue…',
        ['Sélection de variables en annulant certains βj', 'Augmentation des coefficients', 'Régression non-paramétrique', 'Estimation Bayésienne'], [0],
        'Sélection de variables',
        'Pénalité Σ|βj| ; sparse solutions, utile en haute dimension.',
        'Tibshirani, 1996.'),
      q('q8', 'Un modèle GMM s\'estime via…',
        ['Minimisation de moments empiriques pondérés', 'Maximisation de la vraisemblance', 'Moindres carrés simples', 'Bootstrap'], [0],
        'Moments empiriques',
        'Generalized Method of Moments ; ne suppose pas de loi paramétrique complète.',
        'Hansen, 1982 (Nobel 2013).'),
      q('q9', 'La méthode bootstrap consiste à…',
        ['Ré-échantillonner avec remise pour estimer l\'incertitude', 'Réduire la dimension', 'Lisser une série', 'Détecter les outliers'], [0],
        'Ré-échantillonnage avec remise',
        'Efron 1979 ; alternative non-paramétrique pour CI, biais, écarts-types.',
        'Efron, 1979.')
    ]
  },
  {
    titre: 'Finale Machine learning et IA',
    theme: 'Intelligence artificielle',
    domain: ML_NAME,
    questions: [
      q('q1', 'Quelle bibliothèque Python est la plus utilisée pour le ML classique ?',
        ['scikit-learn', 'TensorFlow', 'PyTorch', 'Keras'], [0],
        'scikit-learn',
        'Algorithmes classiques uniformisés via fit/predict ; pipeline, GridSearchCV, métriques.',
        'Pedregosa et al., 2011.'),
      q('q2', 'Quels frameworks dominent le deep learning aujourd\'hui ?',
        ['PyTorch et TensorFlow', 'Theano et Caffe', 'Torch et MXNet', 'JAX et XGBoost'], [0],
        'PyTorch et TensorFlow',
        'PyTorch (Meta) prédominant en recherche ; TensorFlow/Keras encore présent en industrie.',
        '—'),
      q('q3', 'Le terme "overfitting" désigne…',
        ['Un modèle qui mémorise l\'entraînement et généralise mal', 'Une convergence trop rapide', 'Une under-parameterization', 'Un biais constant'], [0],
        'Sur-apprentissage',
        'Signes : faible train error, grand test error ; remèdes : régularisation, plus de données, simplification.',
        'James et al., ISLR.'),
      q('q4', 'La validation croisée k-fold consiste à…',
        ['Diviser les données en k blocs et entraîner k fois en alternant le bloc de test', 'Doubler les données', 'Répéter le test final k fois', 'Bootstrapper les résidus'], [0],
        'k blocs, k entraînements',
        'k = 5 ou 10 ; estime la performance hors-échantillon.',
        'Stone, 1974.'),
      q('q5', 'BERT (NLP) est un modèle…',
        ['Encoder Transformer bidirectionnel pré-entraîné sur masked language modeling', 'Decoder Transformer comme GPT', 'RNN avec attention', 'Réseau convolutif 1D'], [0],
        'Encoder Transformer bidirectionnel',
        'Devlin et al. 2018 ; pré-entraîné sur MLM + NSP, fine-tuné sur tâches downstream.',
        'Devlin et al., 2018.'),
      q('q6', 'GPT est un modèle…',
        ['Decoder Transformer auto-régressif (prédit le token suivant)', 'Encoder bidirectionnel', 'CNN appliqué au texte', 'Word2Vec amélioré'], [0],
        'Decoder Transformer auto-régressif',
        'Generative Pre-trained Transformer ; entraînement causal sur de grands corpus.',
        'Radford et al., 2018-2023.'),
      q('q7', 'Quelle technique d\'augmentation est typique en vision par ordinateur ?',
        ['Rotation, flip, crop, color jitter', 'Tokenization', 'Stemming', 'Lemmatization'], [0],
        'Rotation/flip/crop/jitter',
        'Multiplie artificiellement les données ; réduit l\'overfitting.',
        'Goodfellow et al., 2016.'),
      q('q8', 'Le RAG (Retrieval-Augmented Generation) combine…',
        ['Un index documentaire et un LLM pour générer des réponses contextuelles', 'Plusieurs CNN en parallèle', 'Du reinforcement learning et de la régression', 'Un autoencoder et un GAN'], [0],
        'Index + LLM',
        'Lewis et al. 2020 ; améliore la précision et limite les hallucinations.',
        'Lewis et al., 2020.'),
      q('q9', 'Quelle métrique est usuelle pour évaluer les classifieurs déséquilibrés ?',
        ['F1-score ou AUC-PR', 'Accuracy', 'MSE', 'R²'], [0],
        'F1-score ou AUC-PR',
        'Accuracy trompeuse si classes déséquilibrées ; PR-AUC met l\'accent sur la classe rare.',
        'Saito & Rehmsmeier, 2015.')
    ]
  },
  {
    titre: 'Finale Suivi-évaluation des projets',
    theme: 'Suivi et évaluation',
    domain: SE_NAME,
    questions: [
      q('q1', 'La pyramide des résultats du PNUD comprend, du plus immédiat au plus large :',
        ['Inputs → Activités → Produits → Effets → Impact', 'Impact → Effets → Produits → Activités → Inputs', 'Outputs → Outcomes → Goals → Mission', 'Inputs → Outputs → Outcomes → Vision'], [0],
        'Inputs → Activités → Produits → Effets → Impact',
        'Chaîne logique standard ; les 3 premiers niveaux sont la "sphère de contrôle" du projet.',
        'PNUD HPMEDR, 2009.'),
      q('q2', 'Le ROI social (SROI) calcule…',
        ['Le ratio bénéfices sociaux monétisés sur coûts', 'Le rendement financier interne', 'L\'efficience pure', 'Le délai de récupération'], [0],
        'Bénéfices sociaux / coûts',
        'Methodology SROI Network ; monétarise les impacts sociaux et environnementaux.',
        'Nef, A Guide to SROI, 2009.'),
      q('q3', 'Au FIDA, le système RIMS (=SYGRI) couvre combien de niveaux d\'indicateurs ?',
        ['Trois niveaux (1er = produits ; 2e = effets ; 3e = impact)', 'Deux niveaux', 'Cinq niveaux', 'Un seul niveau global'], [0],
        '3 niveaux',
        'Indicateurs standardisés par catégorie ; permet l\'agrégation à l\'échelle du portefeuille FIDA.',
        'IFAD, RIMS Handbook.'),
      q('q4', 'Quel est l\'IRR/TRI minimal généralement exigé par les bailleurs pour valider un projet ?',
        ['12 % en moyenne (varie selon le secteur)', '5 %', '25 %', '50 %'], [0],
        '≈ 12 %',
        'Banque mondiale, BAD, AFD utilisent souvent 10-12 % comme taux d\'actualisation économique.',
        'World Bank Economic Analysis Guidelines.'),
      q('q5', 'Un évaluation "ex-ante" se réalise…',
        ['Avant le démarrage du projet (faisabilité, design)', 'À mi-parcours', 'À la fin', 'Trois ans après la clôture'], [0],
        'Avant le démarrage',
        'Évalue pertinence, faisabilité, théorie du changement, risques.',
        'OECD/DAC Glossary.'),
      q('q6', 'Le CGAP est une référence pour l\'évaluation…',
        ['Des programmes de microfinance et inclusion financière', 'De la gouvernance', 'Du secteur agricole', 'De l\'éducation'], [0],
        'Microfinance / inclusion',
        'Consultative Group to Assist the Poor, hébergé par la Banque mondiale.',
        'CGAP, World Bank.'),
      q('q7', 'Quelle technique combine méthodes quantitatives et qualitatives ?',
        ['Mixed methods', 'Big data analytics', 'Régression OLS', 'Analyse factorielle'], [0],
        'Mixed methods',
        'Triangulation : RCT + enquêtes + focus groups + études de cas.',
        'Bamberger, "Mixed Methods in IE", 2012.'),
      q('q8', 'La théorie du programme (program theory) précise…',
        ['Comment et pourquoi l\'intervention est censée produire les résultats attendus', 'Le budget détaillé', 'L\'organigramme', 'Le calendrier d\'exécution'], [0],
        'Mécanismes causaux du programme',
        'Description explicite de la chaîne d\'effets et hypothèses ; base de l\'évaluation par théorie.',
        'Funnell & Rogers, "Purposeful Program Theory", 2011.'),
      q('q9', 'Quel principe interdit qu\'une intervention nuise aux bénéficiaires ?',
        ['"Do no harm"', '"Pareto-optimal"', '"Cost-effective"', '"Triple bottom line"'], [0],
        'Do no harm',
        'Principe transversal en aide humanitaire et développement ; OCHA, Sphere Standards.',
        'Anderson, "Do No Harm", 1999.')
    ]
  }
];

module.exports = { m1Packs, m2Packs, m3Packs, STAT_NAME, ML_NAME, SE_NAME };
