// =====================================================================
// data_extra_v241.js — v2.41 : approfondissement AGRIBUSINESS
//   • Compte d'exploitation et gestion des exploitations/entreprises
//   • Business models adaptés à l'agribusiness
//   • Montage et gestion de projets agricoles
//   • Chaînes de valeur agricoles intégrées
//   • Agriculture contractuelle
//   • Commerce international des produits agricoles
// =====================================================================

const { mk, packify } = require('./data_extra_v230b.js');
const { packM2, packM3 } = require('./data_extra_v235a.js');

const AGRI = 'Économie agricole et agribusiness';
const TH = 'Agribusiness et gestion';

// =====================================================================
// M1 — 24 questions (6 packs de 4)
// =====================================================================
const m1 = [

// --- Compte d'exploitation & gestion (8) -----------------------------
mk('Dans le compte d\'exploitation d\'une ferme, la marge brute d\'une culture se calcule comme…',
  'Produit brut de la culture − charges variables qui lui sont affectées',
  'Chiffre d\'affaires total − toutes les charges fixes',
  'Produit brut + subventions − impôts',
  'Ventes − amortissements du matériel',
  'La marge brute (produit brut − charges opérationnelles : semences, engrais, produits, main-d\'œuvre saisonnière) est l\'outil de comparaison des ateliers : les charges fixes, communes, ne lui sont pas imputées.',
  'https://fr.wikipedia.org/wiki/Marge_brute'),
mk('Le produit brut d\'un atelier maïs comprend les ventes ET…',
  'L\'autoconsommation et les variations de stocks valorisées',
  'Uniquement les subventions reçues',
  'Les emprunts de campagne obtenus',
  'La valeur du matériel acheté dans l\'année',
  'Le produit brut = ventes + autoconsommation + dons + stock final − stock initial, le tout valorisé au prix du marché : l\'autoconsommation est un vrai produit, souvent majeur en exploitation familiale.',
  'https://fr.wikipedia.org/wiki/Comptabilit%C3%A9_agricole'),
mk('Les charges de structure (fixes) d\'une exploitation agricole sont celles qui…',
  'Ne varient pas avec les surfaces ou volumes produits à court terme',
  'Augmentent proportionnellement aux quantités récoltées',
  'Concernent uniquement les intrants importés',
  'Sont payées seulement les années de bonne récolte',
  'Amortissements, fermage, salaires permanents, assurances : elles courent quelle que soit la production — d\'où l\'enjeu de les couvrir par la somme des marges brutes.',
  'https://fr.wikipedia.org/wiki/Charge_fixe'),
mk('L\'excédent brut d\'exploitation (EBE) d\'une entreprise agricole mesure…',
  'Le cash dégagé par l\'exploitation avant amortissements et frais financiers',
  'Le bénéfice net après impôt',
  'La valeur totale du cheptel',
  'Le montant des subventions d\'équipement',
  'EBE = produits d\'exploitation − charges opérationnelles − charges de personnel : il finance annuités, autofinancement et prélèvements privés — l\'indicateur clé de viabilité.',
  'https://fr.wikipedia.org/wiki/Exc%C3%A9dent_brut_d%27exploitation'),
mk('Le coût de production d\'un kilogramme de riz paddy s\'obtient en divisant…',
  'L\'ensemble des charges (variables + fixes imputées) par les kg produits',
  'Le prix de vente par le rendement',
  'Les seules charges d\'engrais par la surface',
  'La marge brute par le nombre de sacs',
  'Coût de revient unitaire = charges totales imputables / production totale : comparé au prix de vente, il détermine la marge unitaire et le seuil de compétitivité.',
  'https://fr.wikipedia.org/wiki/Co%C3%BBt_de_production'),
mk('Une exploitation dégage 3 000 000 FCFA de marges brutes ; ses charges de structure sont de 1 800 000 FCFA dont 600 000 d\'amortissements. Son EBE est de…',
  '1 800 000 FCFA',
  '1 200 000 FCFA',
  '3 000 000 FCFA',
  '600 000 FCFA',
  'EBE = Σ marges brutes − charges de structure HORS amortissements = 3 000 000 − (1 800 000 − 600 000) = 1 800 000 FCFA. L\'amortissement, charge calculée, se déduit ensuite pour le résultat.',
  'https://fr.wikipedia.org/wiki/Exc%C3%A9dent_brut_d%27exploitation'),
mk('Le plan de trésorerie de campagne d\'une exploitation sert à…',
  'Anticiper mois par mois les décaissements et encaissements pour éviter l\'impasse',
  'Calculer l\'impôt foncier annuel',
  'Mesurer la fertilité des sols',
  'Fixer le prix de vente au marché',
  'Les dépenses (intrants, main-d\'œuvre) précèdent de plusieurs mois les recettes de récolte : le plan de trésorerie dimensionne le crédit de campagne et évite de brader la récolte à la soudure.',
  'https://fr.wikipedia.org/wiki/Plan_de_tr%C3%A9sorerie'),
mk('Le carnet de bord technico-économique d\'une exploitation permet avant tout de…',
  'Enregistrer opérations, quantités et coûts pour calculer les marges réelles',
  'Remplacer la déclaration fiscale',
  'Garantir un prix minimum au producteur',
  'Obtenir automatiquement un label bio',
  'Sans enregistrement (itinéraire technique, intrants, temps de travaux, ventes), pas de coût de revient fiable ni de comparaison entre parcelles, campagnes ou pairs (réseaux de fermes de référence).',
  'https://fr.wikipedia.org/wiki/Gestion_agricole'),

// --- Business model & montage de projet (8) --------------------------
mk('Dans le Business Model Canvas appliqué à l\'agribusiness, la « proposition de valeur » désigne…',
  'Ce qui rend l\'offre unique et utile pour un segment de clients donné',
  'Le montant du capital social de départ',
  'La liste des équipements de l\'usine',
  'Le taux d\'intérêt du crédit bancaire',
  'Exemples : jus « 100 % ananas du Togo » traçable, poulet local abattu aux normes, soja non-OGM certifié : la proposition de valeur répond à un besoin client précis, pas à ce que l\'on sait produire.',
  'https://fr.wikipedia.org/wiki/Business_Model_Canvas'),
mk('Le modèle « nucleus estate + outgrowers » (noyau + planteurs satellites) consiste à…',
  'Combiner une plantation-usine centrale et des producteurs contractuels alentour',
  'Vendre uniquement sur le marché de gros urbain',
  'Produire sans aucun contrat avec des tiers',
  'Importer la matière première transformée',
  'Le noyau garantit un volume de base à l\'usine et diffuse l\'itinéraire technique ; les outgrowers complètent l\'approvisionnement sous contrat — modèle classique de l\'huile de palme ou de la canne.',
  'https://fr.wikipedia.org/wiki/Agriculture_contractuelle'),
mk('Pour une PME de transformation agroalimentaire, les « flux de revenus » du canvas incluent typiquement…',
  'Ventes du produit principal, sous-produits valorisés et prestations annexes',
  'Les seuls apports des actionnaires',
  'Les subventions comme unique ressource durable',
  'Les dettes fournisseurs',
  'Une huilerie de soja vend l\'huile ET le tourteau (aliment bétail), parfois la prestation de trituration : la viabilité vient souvent des coproduits et services, pas du seul produit phare.',
  'https://fr.wikipedia.org/wiki/Mod%C3%A8le_d%27affaires'),
mk('Une étude de faisabilité complète d\'un projet agro-industriel couvre…',
  'Marché, technique, organisation, finances et impacts environnementaux et sociaux',
  'Uniquement le calcul du TRI',
  'La seule disponibilité du terrain',
  'Le choix du logo et du slogan',
  'Étude de marché (demande, prix, concurrence), faisabilité technique (procédé, approvisionnement), montage institutionnel, analyse financière (VAN/TRI) et sauvegardes E&S : un volet faible invalide le tout.',
  'https://fr.wikipedia.org/wiki/%C3%89tude_de_faisabilit%C3%A9'),
mk('Pour un verger d\'anacardiers qui n\'entre en pleine production qu\'en année 6, l\'analyse financière doit…',
  'Actualiser des flux négatifs initiaux puis positifs sur la durée de vie du verger',
  'Ignorer les premières années sans recettes',
  'Compter la récolte de l\'année 1 comme normale',
  'Amortir les arbres sur une seule campagne',
  'Les cultures pérennes ont un profil de flux très étalé : VAN et TRI se calculent sur 15-25 ans, avec trésorerie de soudure des années improductives — c\'est là que meurent les projets mal financés.',
  'https://fr.wikipedia.org/wiki/Valeur_actuelle_nette'),
mk('Dans un plan d\'affaires agricole, le besoin en fonds de roulement (BFR) initial correspond…',
  'Au financement des charges de campagne avant les premières recettes',
  'Au prix d\'achat du terrain uniquement',
  'À la valeur des bâtiments amortis',
  'Aux dividendes prévus la première année',
  'Intrants, salaires, énergie et stocks se paient des mois avant l\'encaissement des ventes : sous-estimer le BFR est la première cause d\'asphyxie des entreprises agricoles naissantes.',
  'https://fr.wikipedia.org/wiki/Besoin_en_fonds_de_roulement'),
mk('Le plan de financement d\'un projet agribusiness équilibre…',
  'Emplois durables (investissements, BFR) et ressources durables (fonds propres, emprunts, subventions)',
  'Recettes et dépenses du seul premier mois',
  'Salaires et impôts',
  'Actif circulant et chiffre d\'affaires',
  'La règle d\'or : les emplois longs se financent par des ressources longues ; financer une chambre froide par un découvert court expose au retrait brutal du financement.',
  'https://fr.wikipedia.org/wiki/Plan_de_financement'),
mk('Le suivi d\'exécution d\'un projet d\'entreprise agricole croise en permanence…',
  'Avancement physique, consommation budgétaire et indicateurs techniques',
  'Le seul relevé bancaire',
  'La météo et rien d\'autre',
  'Les réseaux sociaux de l\'entreprise',
  'Taux d\'exécution physique vs financier, rendements réels vs prévus, coûts unitaires : les écarts déclenchent des actions correctives (replanification, renégociation) avant que le projet ne dérive.',
  'https://fr.wikipedia.org/wiki/Gestion_de_projet'),

// --- CVA intégrée, contractualisation, export (8) --------------------
mk('Une chaîne de valeur agricole « intégrée » se caractérise par…',
  'La coordination organisée des maillons, de l\'intrant au consommateur',
  'La vente exclusive au bord du champ',
  'L\'absence totale d\'intermédiaires et de règles',
  'La production sans transformation ni commercialisation',
  'Intégration = flux physiques, financiers et d\'information coordonnés (contrats, standards, traçabilité, financement de chaîne) — par opposition aux transactions ponctuelles au comptant.',
  'https://fr.wikipedia.org/wiki/Cha%C3%AEne_de_valeur'),
mk('Le financement « de chaîne de valeur » (value chain finance) repose sur…',
  'La solidité des relations commerciales de la chaîne plutôt que sur des garanties classiques',
  'L\'hypothèque systématique des terres du producteur',
  'Le financement exclusif par l\'État',
  'Des dons sans remboursement',
  'La banque prête au producteur PARCE QU\'un acheteur fiable s\'est engagé (contrat tripartite, domiciliation des paiements) : le flux commercial sert de garantie — clé quand le foncier n\'est pas titré.',
  'https://fr.wikipedia.org/wiki/Financement_de_la_cha%C3%AEne_de_valeur'),
mk('Dans la typologie FAO de l\'agriculture contractuelle, le modèle « multipartite » associe…',
  'Entreprise, producteurs et acteurs tiers (État, banque, ONG) dans le dispositif contractuel',
  'Deux producteurs entre eux uniquement',
  'L\'entreprise et ses seuls salariés',
  'Des acheteurs anonymes au marché de gros',
  'Aux côtés des modèles centralisé, nucleus estate, intermédiaire et informel, le modèle multipartite mobilise banque (crédit), État ou ONG (appui-conseil) autour du couple acheteur-producteurs.',
  'https://fr.wikipedia.org/wiki/Agriculture_contractuelle'),
mk('Dans un contrat de production, la fourniture d\'intrants à crédit par l\'acheteur est généralement remboursée…',
  'Par déduction sur la valeur de la récolte livrée',
  'En espèces avant le semis',
  'Par la banque centrale',
  'Jamais : c\'est un don définitif',
  'L\'acheteur avance semences/engrais et récupère leur coût à la livraison — le producteur accède aux intrants sans garantie bancaire ; le risque : la vente parallèle qui esquive le remboursement.',
  'https://fr.wikipedia.org/wiki/Agriculture_contractuelle'),
mk('Le « side-selling » (vente parallèle), principal risque de l\'agriculture contractuelle, désigne…',
  'La vente de la récolte sous contrat à un tiers offrant un prix spot supérieur',
  'La vente de produits transformés en ligne',
  'L\'exportation légale via un transitaire',
  'La vente des terres de l\'exploitation',
  'Quand le prix du marché dépasse le prix contractuel, la tentation de vendre ailleurs ruine l\'acheteur qui a préfinancé. Antidotes : prix indexés, relation de long terme, services liés, pression du groupe.',
  'https://fr.wikipedia.org/wiki/Agriculture_contractuelle'),
mk('L\'Incoterm FOB (Free On Board) signifie que l\'exportateur togolais de soja supporte les coûts et risques…',
  'Jusqu\'au chargement à bord du navire au port de Lomé',
  'Jusqu\'à l\'entrepôt de l\'acheteur en Europe',
  'Uniquement jusqu\'à la sortie du champ',
  'Y compris l\'assurance maritime et le fret jusqu\'au port d\'arrivée',
  'FOB : le vendeur dédouane à l\'export et charge à bord ; fret maritime et assurance incombent à l\'acheteur. En CIF, le vendeur paie en plus coût, assurance et fret jusqu\'au port de destination.',
  'https://fr.wikipedia.org/wiki/Incoterm'),
mk('Les mesures SPS (sanitaires et phytosanitaires) qui conditionnent l\'export agricole visent…',
  'La protection de la santé humaine, animale et végétale (résidus, ravageurs, hygiène)',
  'La fixation des prix mondiaux',
  'La conception des emballages marketing',
  'Le calcul des droits de douane',
  'LMR de pesticides, aflatoxines, certificats phytosanitaires : l\'accord SPS de l\'OMC encadre ces exigences, premier motif de refoulement des produits africains aux frontières des marchés riches.',
  'https://fr.wikipedia.org/wiki/Accord_sur_les_mesures_sanitaires_et_phytosanitaires'),
mk('L\'« escalade tarifaire » pratiquée par certains importateurs pénalise les pays agricoles car elle…',
  'Taxe davantage les produits transformés que les matières premières brutes',
  'Supprime tous les droits de douane',
  'Ne concerne que les produits industriels',
  'Subventionne la transformation locale africaine',
  'Cacao brut à droit quasi nul, chocolat taxé : l\'escalade décourage la transformation à l\'origine et verrouille les pays producteurs dans l\'export de matières brutes à faible valeur.',
  'https://fr.wikipedia.org/wiki/Escalade_tarifaire')
];

// =====================================================================
// M2 — 3 packs de 6 (points 1 → 6)
// =====================================================================
const m2 = [

packM2(AGRI, TH, 'Gestion de l\'exploitation agricole — Face-à-face', [
  mk('Quel document enregistre, campagne après campagne, produits et charges d\'une exploitation ?',
    'Le compte d\'exploitation', 'Le certificat foncier', 'Le bulletin météo décadaire', 'Le procès-verbal d\'assemblée villageoise',
    'Le compte d\'exploitation retrace produits (ventes, autoconsommation, stocks) et charges de la campagne : c\'est la base du diagnostic de gestion.',
    'https://fr.wikipedia.org/wiki/Compte_de_r%C3%A9sultat'),
  mk('La différence essentielle entre charges opérationnelles et charges de structure tient à…',
    'Leur lien direct ou non avec le volume produit', 'Leur paiement en espèces ou en nature', 'Leur caractère légal ou illégal', 'Leur ancienneté comptable',
    'Opérationnelles (semences, engrais, saisonniers) : proportionnelles à l\'activité et affectables par atelier ; de structure (amortissements, fermage, permanents) : indépendantes des surfaces à court terme.',
    'https://fr.wikipedia.org/wiki/Charge_variable'),
  mk('Une marge brute maïs de 260 000 FCFA/ha avec 200 000 FCFA de charges opérationnelles correspond à un produit brut de…',
    '460 000 FCFA/ha', '60 000 FCFA/ha', '260 000 FCFA/ha', '520 000 FCFA/ha',
    'Produit brut = marge brute + charges opérationnelles = 260 000 + 200 000 = 460 000 FCFA/ha.',
    'https://fr.wikipedia.org/wiki/Marge_brute'),
  mk('L\'annuité d\'un emprunt d\'équipement se rembourse sainement sur…',
    'L\'excédent brut d\'exploitation dégagé par la ferme', 'Les charges opérationnelles', 'Le produit brut avant charges', 'Le capital social uniquement',
    'L\'EBE finance annuités, prélèvements familiaux et autofinancement : si annuités > 50-60 % de l\'EBE, l\'exploitation est en zone rouge de remboursement.',
    'https://fr.wikipedia.org/wiki/Exc%C3%A9dent_brut_d%27exploitation'),
  mk('Le seuil de rentabilité en volume d\'un atelier avicole s\'obtient en divisant les charges fixes par…',
    'La marge sur coût variable unitaire (prix − coût variable par poulet)', 'Le prix de vente du poulet', 'Le coût total de l\'aliment', 'Le nombre de sujets par bande',
    'SR(volume) = CF / MCV unitaire : chaque poulet vendu contribue de sa MCV à couvrir les fixes ; au-delà du seuil, elle devient du résultat.',
    'https://fr.wikipedia.org/wiki/Seuil_de_rentabilit%C3%A9'),
  mk('Comparer ses coûts et rendements à ceux d\'un réseau de fermes de référence permet surtout de…',
    'Situer ses performances et cibler les marges de progrès atelier par atelier', 'Obtenir un prix de vente garanti par l\'État', 'Éviter de tenir sa propre comptabilité', 'Remplacer l\'analyse de sol',
    'Le benchmarking technico-économique (type réseaux de gestion) révèle les écarts anormaux — coût d\'aliment, mortalité, rendement — et les pratiques des meilleurs.',
    'https://fr.wikipedia.org/wiki/Analyse_comparative'),
]),

packM2(AGRI, TH, 'Agriculture contractuelle et chaînes de valeur — Face-à-face', [
  mk('Un contrat agricole qui fixe à l\'avance quantité, qualité, calendrier et mode de prix relève de…',
    'L\'agriculture contractuelle', 'La vente au comptant sur le marché spot', 'Du métayage coutumier', 'De la réquisition administrative',
    'Le contrat de production/commercialisation sécurise le débouché du producteur et l\'approvisionnement de l\'acheteur — fondement des chaînes de valeur organisées.',
    'https://fr.wikipedia.org/wiki/Agriculture_contractuelle'),
  mk('L\'« agrégateur » d\'une chaîne de valeur est l\'acteur qui…',
    'Fédère de nombreux petits producteurs autour d\'un débouché et de services communs', 'Fixe la fiscalité agricole nationale', 'Transporte uniquement les marchandises', 'Certifie les semences en laboratoire',
    'L\'agrégateur (entreprise, coopérative, union) mutualise intrants, conseil, collecte et négociation : il abaisse les coûts de transaction entre l\'aval et des milliers d\'exploitations.',
    'https://fr.wikipedia.org/wiki/Coop%C3%A9rative_agricole'),
  mk('Un prix contractuel indexé (prix plancher + part du prix de marché) vise principalement à…',
    'Réduire la tentation de vente parallèle quand les cours montent', 'Suppimer toute variation de revenu', 'Garantir un profit à l\'État', 'Bloquer les prix à la consommation',
    'Le producteur profite partiellement des hausses (moins d\'intérêt à trahir le contrat) tout en gardant un plancher : meilleur compromis incitations/sécurité que le prix fixe pur.',
    'https://fr.wikipedia.org/wiki/Agriculture_contractuelle'),
  mk('Dans un montage tripartite banque–agrégateur–producteurs, la « domiciliation » des paiements signifie que…',
    'L\'acheteur paie sur un compte dédié où la banque prélève d\'abord le crédit', 'Chaque producteur reçoit son argent en espèces au champ', 'La banque achète elle-même la récolte', 'Les paiements transitent par la mairie',
    'Le circuit fermé des flux (récolte → acheteur → compte domicilié → remboursement → solde au producteur) sécurise la banque sans hypothèque : cœur du financement de chaîne de valeur.',
    'https://fr.wikipedia.org/wiki/Financement_de_la_cha%C3%AEne_de_valeur'),
  mk('L\'intégration verticale d\'un agro-industriel (amont ou aval) se justifie économiquement quand…',
    'Les coûts de transaction du marché dépassent les coûts d\'organisation interne', 'Les prix mondiaux sont parfaitement stables', 'La main-d\'œuvre est gratuite', 'La demande disparaît',
    'Williamson : actifs spécifiques, incertitude et opportunisme renchérissent le recours au marché ; l\'entreprise internalise alors (plantation propre, flotte, distribution).',
    'https://fr.wikipedia.org/wiki/Int%C3%A9gration_verticale'),
  mk('La traçabilité « du champ à l\'assiette » exigée par les chaînes intégrées repose sur…',
    'L\'identification des lots et l\'enregistrement de chaque étape (parcelle, collecte, transformation)', 'La bonne réputation orale du vendeur', 'Le seul contrôle au port d\'arrivée', 'Un prix de vente plus bas',
    'Codes lots, registres de collecte, géolocalisation des parcelles : la traçabilité conditionne l\'accès aux marchés exigeants (UE, bio, cacao « zéro déforestation »).',
    'https://fr.wikipedia.org/wiki/Tra%C3%A7abilit%C3%A9_alimentaire'),
]),

packM2(AGRI, TH, 'Commerce international des produits agricoles — Face-à-face', [
  mk('Entre FOB Lomé et CIF Rotterdam, la différence de prix couvre…',
    'Le fret maritime et l\'assurance jusqu\'au port de destination', 'La TVA togolaise', 'Le salaire des dockers de Lomé uniquement', 'Les droits de douane européens',
    'CIF = FOB + fret + assurance : comparer des prix internationaux exige de toujours préciser l\'Incoterm et le port de référence.',
    'https://fr.wikipedia.org/wiki/Incoterm'),
  mk('Le certificat phytosanitaire qui accompagne un lot d\'ananas exporté est délivré par…',
    'L\'autorité nationale de protection des végétaux du pays exportateur', 'La compagnie maritime', 'Le supermarché de destination', 'La banque de l\'exportateur',
    'L\'organisation nationale de protection des végétaux (au Togo, la direction en charge — DPV) atteste l\'absence d\'organismes de quarantaine, conformément à la CIPV.',
    'https://fr.wikipedia.org/wiki/Certificat_phytosanitaire'),
  mk('La certification GlobalG.A.P. exigée par les distributeurs européens porte sur…',
    'Les bonnes pratiques agricoles à la production (sécurité sanitaire, environnement, travailleurs)', 'Le taux de change du FCFA', 'La couleur des emballages', 'Le niveau des droits de douane',
    'Référentiel privé de pré-ferme à la sortie d\'exploitation : enregistrements, usage raisonné des pesticides, hygiène, audités par des organismes tiers — passeport de fait pour la grande distribution.',
    'https://fr.wikipedia.org/wiki/GlobalGAP'),
  mk('Pour se couvrir contre la baisse du cours du cacao d\'ici la récolte, un exportateur peut…',
    'Vendre des contrats à terme (futures) sur le marché organisé', 'Acheter davantage de cacao physique', 'Attendre en espérant la hausse', 'Réduire la qualité de ses fèves',
    'La vente à terme fige aujourd\'hui le prix de la vente future : la perte éventuelle sur le physique est compensée par le gain sur le contrat (couverture courte).',
    'https://fr.wikipedia.org/wiki/Contrat_%C3%A0_terme'),
  mk('L\'initiative européenne « Tout sauf les armes » (TSA/EBA) accorde aux PMA comme le Togo…',
    'Un accès au marché de l\'UE sans droits ni quotas (hors armes)', 'Une subvention directe aux producteurs', 'Un taux de change préférentiel', 'La suppression des normes SPS',
    'L\'accès en franchise ne dispense PAS des exigences sanitaires et de traçabilité : la préférence tarifaire ne vaut que si l\'on franchit la barrière des normes.',
    'https://fr.wikipedia.org/wiki/Tout_sauf_les_armes'),
  mk('Les règles d\'origine de la ZLECAf déterminent…',
    'Le caractère « africain » d\'un produit, condition des préférences tarifaires', 'Le prix minimum garanti continental', 'La langue des contrats commerciaux', 'Le pavillon des navires',
    'Critères de transformation substantielle ou de valeur ajoutée locale : sans origine conforme, pas de franchise ZLECAf — enjeu direct pour les agro-transformateurs togolais.',
    'https://fr.wikipedia.org/wiki/Zone_de_libre-%C3%A9change_continentale_africaine'),
])
];

// =====================================================================
// M3 — 2 packs de 9 (finale, buzz)
// =====================================================================
const m3 = [

packM3(AGRI, TH, 'Agribusiness : gestion, business models et projets — Finale', [
  mk('L\'indicateur de gestion qui compare les ateliers d\'une même ferme indépendamment des charges fixes est…',
    'La marge brute par atelier', 'Le résultat net global', 'Le total du bilan', 'Le chiffre d\'affaires TTC',
    'Les charges fixes étant communes, seule la marge brute isole la performance propre de chaque production.',
    'https://fr.wikipedia.org/wiki/Marge_brute'),
  mk('Amortir un tracteur de 15 000 000 FCFA sur 10 ans en linéaire donne une dotation annuelle de…',
    '1 500 000 FCFA', '150 000 FCFA', '15 000 000 FCFA', '3 000 000 FCFA',
    'Dotation = valeur amortissable / durée = 15 000 000/10 : charge calculée qui étale le coût du matériel sur sa vie utile.',
    'https://fr.wikipedia.org/wiki/Amortissement_comptable'),
  mk('Le « pitch » d\'un business model agribusiness doit d\'abord convaincre sur…',
    'Le problème client résolu et le marché visé', 'La marque du véhicule du promoteur', 'Le nombre de pages du document', 'La couleur du logo',
    'Investisseurs et banquiers financent une réponse rentable à une demande réelle : marché d\'abord, technique ensuite.',
    'https://fr.wikipedia.org/wiki/Business_Model_Canvas'),
  mk('Dans le canvas, les « partenaires clés » d\'une laiterie togolaise incluent typiquement…',
    'Éleveurs collecteurs, transporteurs frigorifiques et distributeurs', 'Ses concurrents directs uniquement', 'Les clients finaux', 'Les impôts locaux',
    'Les partenaires clés sécurisent les ressources critiques (lait cru, chaîne du froid, débouchés) que l\'entreprise ne possède pas en propre.',
    'https://fr.wikipedia.org/wiki/Business_Model_Canvas'),
  mk('Un projet agricole a une VAN positive au taux de 12 % : cela signifie que…',
    'Il crée de la valeur après rémunération du capital à 12 %', 'Son TRI est inférieur à 12 %', 'Il est sans aucun risque', 'Ses recettes annuelles sont constantes',
    'VAN > 0 au taux d\'actualisation retenu ⇔ TRI > 12 % : le projet rapporte plus que le coût d\'opportunité des fonds.',
    'https://fr.wikipedia.org/wiki/Valeur_actuelle_nette'),
  mk('Le délai de récupération (payback) d\'un investissement agricole mesure…',
    'Le temps nécessaire pour que les flux cumulés remboursent la mise initiale', 'La durée de vie du matériel', 'Le délai de paiement des clients', 'La période de garantie du fournisseur',
    'Simple et parlant pour la trésorerie, mais aveugle aux flux postérieurs : à compléter par VAN/TRI.',
    'https://fr.wikipedia.org/wiki/D%C3%A9lai_de_r%C3%A9cup%C3%A9ration'),
  mk('L\'analyse de sensibilité d\'un plan d\'affaires agro consiste à…',
    'Tester la rentabilité quand prix, rendements ou coûts varient', 'Interroger les voisins du site', 'Changer de banque chaque année', 'Réduire la taille de l\'étude',
    'Rendement −20 %, prix −15 %, intrants +25 % : si la VAN résiste aux scénarios pessimistes, le projet est robuste ; sinon, prévoir des atténuations.',
    'https://fr.wikipedia.org/wiki/Analyse_de_sensibilit%C3%A9'),
  mk('Séparer la caisse de l\'exploitation de celle du ménage est une règle de gestion qui permet…',
    'De connaître la vraie rentabilité et de professionnaliser l\'entreprise', 'De payer moins d\'impôts illégalement', 'D\'éviter de rembourser les crédits', 'De cacher les revenus au conjoint',
    'La confusion des caisses masque les prélèvements familiaux et fausse toute décision d\'investissement — premier conseil des centres de gestion.',
    'https://fr.wikipedia.org/wiki/Gestion_agricole'),
  mk('Un « agropole » comme la PIA d\'Adétikopé vise à créer de la valeur en…',
    'Concentrant sur un site transformation, logistique et services autour des filières', 'Remplaçant toute production paysanne', 'Interdisant les exportations', 'Supprimant les coopératives',
    'Le parc agro-industriel réduit les coûts (énergie, guichet unique, corridor) et attire les investisseurs de transformation — maillon aval des chaînes de valeur intégrées.',
    'https://fr.wikipedia.org/wiki/Parc_industriel'),
]),

packM3(AGRI, TH, 'De la ferme au marché mondial — Finale', [
  mk('La chaîne de valeur se distingue de la simple filière par l\'accent mis sur…',
    'La valeur créée à chaque maillon et la coordination entre acteurs', 'Le seul transport physique', 'Les statistiques douanières', 'La météo des régions',
    'Analyse filière : flux et acteurs ; approche chaîne de valeur : où se crée la valeur, qui la capte, comment la gouvernance améliore la compétitivité.',
    'https://fr.wikipedia.org/wiki/Cha%C3%AEne_de_valeur'),
  mk('Le modèle contractuel « centralisé » de la FAO correspond à…',
    'Un acheteur unique contractant directement avec de nombreux producteurs', 'Des producteurs sans aucun acheteur', 'Un marché de gros anonyme', 'Une bourse de matières premières',
    'Typique du coton ou de la canne : l\'entreprise centrale fournit intrants et conseil, collecte et paie — avec un fort contrôle qualité.',
    'https://fr.wikipedia.org/wiki/Agriculture_contractuelle'),
  mk('Pour le producteur, l\'avantage central du contrat par rapport au marché spot est…',
    'La sécurisation du débouché et l\'accès aux intrants et au conseil', 'Un prix toujours supérieur au marché', 'L\'absence de toute obligation', 'La propriété de l\'usine',
    'Débouché garanti, intrants préfinancés, itinéraire technique : la contrepartie est l\'engagement de livrer — le contrat échange de la flexibilité contre de la sécurité.',
    'https://fr.wikipedia.org/wiki/Agriculture_contractuelle'),
  mk('Une coopérative qui négocie collectivement le prix du soja de ses membres exerce…',
    'Un pouvoir de marché compensateur face aux acheteurs', 'Une fraude commerciale', 'Un monopole d\'État', 'Une activité bancaire illégale',
    'Galbraith : le « countervailing power » — l\'agrégation rééquilibre la négociation entre des milliers de petits vendeurs et quelques gros acheteurs.',
    'https://fr.wikipedia.org/wiki/Coop%C3%A9rative_agricole'),
  mk('Le conteneur « reefer » utilisé pour l\'ananas frais togolais est…',
    'Un conteneur frigorifique maintenant la chaîne du froid', 'Un sac de jute renforcé', 'Un entrepôt portuaire', 'Un navire spécialisé uniquement',
    'Le maintien de la température de la palettisation au port de destination conditionne la qualité à l\'arrivée : la rupture de chaîne du froid détruit la valeur du lot.',
    'https://fr.wikipedia.org/wiki/Conteneur_frigorifique'),
  mk('La limite maximale de résidus (LMR) dépassée sur un lot exporté vers l\'UE entraîne…',
    'Le refoulement ou la destruction du lot à la frontière', 'Une simple remise de prix', 'Un délai de paiement allongé', 'Un changement d\'Incoterm',
    'Les alertes RASFF européennes frappent régulièrement les produits tropicaux : le respect des LMR se joue au champ (choix et délais avant récolte des traitements).',
    'https://fr.wikipedia.org/wiki/Limite_maximale_de_r%C3%A9sidus'),
  mk('Le label Fairtrade/commerce équitable garantit principalement au producteur…',
    'Un prix minimum et une prime collective de développement', 'L\'absence de tout contrôle', 'Un rendement agronomique doublé', 'Une exonération des taxes togolaises',
    'Prix plancher (filet si les cours chutent) + prime investie collectivement (école, magasin d\'intrants) : la certification a un coût, à comparer aux bénéfices.',
    'https://fr.wikipedia.org/wiki/Commerce_%C3%A9quitable'),
  mk('Sur le marché mondial, le prix du coton togolais dépend principalement…',
    'Des cours internationaux (indice Cotlook A) et du taux de change', 'Du seul décret national annuel', 'Du prix du ciment local', 'De la température à Lomé',
    'Petit pays preneur de prix : le prix au producteur dérive du cours mondial converti en FCFA, moins les coûts de la filière — d\'où l\'intérêt des mécanismes de lissage.',
    'https://fr.wikipedia.org/wiki/Coton'),
  mk('L\'exportation de produits agricoles « hors saison » vers l\'Europe (haricot vert, mangue) exploite…',
    'Le décalage des calendriers de production entre hémisphères et climats', 'Les droits de douane plus élevés', 'La baisse de qualité hivernale africaine', 'L\'interdiction des serres en Europe',
    'La contre-saison est un avantage comparatif temporel : vendre quand l\'offre locale européenne est absente — à condition de maîtriser logistique aérienne/maritime et normes.',
    'https://fr.wikipedia.org/wiki/Exportation')
])
];

// ---------------- Assemblage -----------------------------------------
const m1Packs = packify(AGRI, TH, 'Agribusiness — gestion, projets et marchés', m1);

module.exports = { m1Packs, m2Packs: m2, m3Packs: m3 };
