// =====================================================================
// data_extra_v230e.js — v2.30 : Sciences sociales (+104),
// Culture générale & environnement (+112).
// =====================================================================

const { mk, F } = require('./data_extra_v230b.js');

// ---------------- SCIENCES SOCIALES & POLITIQUES (+104) --------------
const soc = [];
[
 mk('Pour Émile Durkheim, un « fait social » se reconnaît à…','Son extériorité et son pouvoir de contrainte sur les individus','Sa rareté','Son caractère biologique','Son prix',
   'Dans « Les Règles de la méthode sociologique » (1895), Durkheim fonde la sociologie sur l\'étude des faits sociaux « comme des choses ».',
   'https://fr.wikipedia.org/wiki/Fait_social'),
 mk('Max Weber définit l\'État par…','Le monopole de la violence physique légitime sur un territoire','La richesse nationale','La religion officielle','Le nombre de fonctionnaires',
   '« Le Savant et le Politique » (1919) : l\'État revendique avec succès le monopole de la contrainte légitime.',
   'https://fr.wikipedia.org/wiki/Monopole_de_la_violence'),
 mk('Les trois types de domination légitime selon Weber sont…','Traditionnelle, charismatique et légale-rationnelle','Militaire, civile et religieuse','Locale, nationale et mondiale','Ancienne, moderne et future',
   'La domination légale-rationnelle, incarnée par la bureaucratie, caractérise les États modernes.',
   'https://fr.wikipedia.org/wiki/Domination_(sociologie)'),
 mk('Pierre Bourdieu appelle « capital culturel »…','Les ressources culturelles (diplômes, savoirs, biens) qui procurent des avantages sociaux','L\'argent en banque','Les terres agricoles','La force physique',
   'Avec le capital économique et social, il explique la reproduction des inégalités (« Les Héritiers », « La Distinction »).',
   'https://fr.wikipedia.org/wiki/Capital_culturel'),
 mk('L\'habitus chez Bourdieu désigne…','Des dispositions durables acquises par la socialisation, qui orientent pratiques et goûts','Un vêtement','Une loi juridique','Un salaire',
   'Structures structurées et structurantes : l\'habitus relie position sociale et manières d\'agir, de percevoir et de juger.',
   'https://fr.wikipedia.org/wiki/Habitus_(sociologie)'),
 mk('La socialisation primaire s\'opère principalement…','Dans la famille durant l\'enfance','À la retraite','Dans les ambassades','Au supermarché',
   'La famille (puis l\'école) transmet normes et valeurs ; la socialisation secondaire se poursuit dans les groupes, le travail, les médias.',
   'https://fr.wikipedia.org/wiki/Socialisation'),
 mk('La mobilité sociale désigne…','Le changement de position sociale entre générations ou au cours de la vie','Les migrations géographiques uniquement','Le sport','La circulation routière',
   'Les tables de mobilité comparent la position des enfants à celle des parents : mobilité ascendante, descendante ou reproduction.',
   'https://fr.wikipedia.org/wiki/Mobilit%C3%A9_sociale'),
 mk('L\'anomie, chez Durkheim, désigne…','Un affaiblissement des normes qui désoriente les individus','Une maladie contagieuse','Un impôt','Une classe sociale',
   'Étudiée dans « Le Suicide » (1897) : les dérèglements des repères collectifs accroissent notamment le suicide anomique.',
   'https://fr.wikipedia.org/wiki/Anomie'),
 mk('Un sondage représentatif utilise souvent…','La méthode des quotas ou le tirage aléatoire','Les seuls volontaires en ligne','Les amis de l\'enquêteur','Une population entière',
   'Quotas (sexe, âge, CSP…) ou tirage probabiliste visent un échantillon miroir de la population ; la marge d\'erreur dépend de la taille.',
   'https://fr.wikipedia.org/wiki/Sondage_(statistique)'),
 mk('La séparation des pouvoirs distingue…','Législatif, exécutif et judiciaire','Riches, moyens et pauvres','Armée, police et douane','État, régions et communes',
   'Théorisée par Montesquieu (« De l\'esprit des lois », 1748) pour prévenir l\'arbitraire : que « le pouvoir arrête le pouvoir ».',
   'https://fr.wikipedia.org/wiki/S%C3%A9paration_des_pouvoirs'),
 mk('Une constitution est…','La loi fondamentale organisant les pouvoirs publics et garantissant les droits','Un décret ministériel','Un contrat commercial','Un budget',
   'Norme suprême de l\'ordre juridique interne ; au Togo, la Constitution de 1992 a été révisée à plusieurs reprises, notamment en 2019 et 2024.',
   'https://fr.wikipedia.org/wiki/Constitution'),
 mk('La démocratie représentative se caractérise par…','L\'élection de représentants qui exercent le pouvoir au nom du peuple','Le tirage au sort intégral','L\'absence d\'élections','Le pouvoir héréditaire',
   'Le suffrage universel, le pluralisme et la responsabilité des gouvernants en sont les piliers ; le référendum relève de la démocratie directe.',
   'https://fr.wikipedia.org/wiki/D%C3%A9mocratie_repr%C3%A9sentative'),
 mk('L\'État de droit implique…','La soumission de tous, y compris l\'État, au droit, sous contrôle du juge','Le pouvoir absolu du gouvernement','La suppression des tribunaux','La loi du plus fort',
   'Hiérarchie des normes, indépendance de la justice et garantie des libertés distinguent l\'État de droit de l\'État de police.',
   'https://fr.wikipedia.org/wiki/%C3%89tat_de_droit'),
 mk('Le suffrage universel signifie que…','Tous les citoyens majeurs peuvent voter sans condition de fortune','Seuls les propriétaires votent','Le vote est réservé aux hommes','Les étrangers votent partout',
   'Conquête progressive contre le suffrage censitaire ; le Togo l\'applique pour les scrutins nationaux et locaux.',
   'https://fr.wikipedia.org/wiki/Suffrage_universel'),
 mk('La société civile désigne…','Les organisations citoyennes autonomes de l\'État (associations, ONG, syndicats)','L\'armée','Le gouvernement','Les seules entreprises',
   'Contre-pouvoir et partenaire : plaidoyer, services, contrôle citoyen de l\'action publique.',
   'https://fr.wikipedia.org/wiki/Soci%C3%A9t%C3%A9_civile'),
 mk('Le genre, en sciences sociales, renvoie à…','La construction sociale des rôles masculins et féminins','Au seul sexe biologique','À la grammaire','Aux générations',
   'Distinct du sexe biologique, le genre analyse normes, rôles et rapports de pouvoir ; il éclaire les inégalités femmes-hommes.',
   'https://fr.wikipedia.org/wiki/Genre_(sciences_sociales)'),
 mk('Un stéréotype est…','Une croyance simplificatrice et généralisée sur un groupe','Une loi scientifique','Un type de contrat','Un revenu',
   'Les stéréotypes alimentent préjugés (attitudes) et discriminations (comportements) ; les politiques d\'inclusion cherchent à les combattre.',
   'https://fr.wikipedia.org/wiki/St%C3%A9r%C3%A9otype'),
 mk('Le capital social (Putnam) désigne…','Les réseaux, normes de réciprocité et confiance facilitant la coopération','L\'argent des entreprises','Les routes et ponts','Les diplômes',
   '« Bowling Alone » (2000) : l\'engagement associatif et la confiance nourrissent performance démocratique et économique.',
   'https://fr.wikipedia.org/wiki/Capital_social_(sociologie)'),
 mk('L\'observation participante est une méthode…','Qualitative où le chercheur s\'immerge dans le groupe étudié','Statistique par questionnaire','Expérimentale en laboratoire','Comptable',
   'Issue de l\'ethnographie (Malinowski) : comprendre les pratiques « de l\'intérieur », avec un journal de terrain rigoureux.',
   'https://fr.wikipedia.org/wiki/Observation_participante'),
 mk('Un entretien semi-directif se caractérise par…','Un guide de thèmes avec liberté de relance et de parole','Des questions fermées uniquement','L\'absence totale de préparation','Un vote',
   'Entre questionnaire fermé et récit libre : il permet de recueillir représentations et logiques d\'acteurs en profondeur.',
   'https://fr.wikipedia.org/wiki/Entretien_semi-directif'),
 mk('La laïcité de l\'État signifie…','La neutralité de l\'État vis-à-vis des religions et la liberté de conscience','L\'interdiction des religions','Une religion d\'État','Le financement d\'un seul culte',
   'Séparation des ordres politique et religieux ; le Togo est une république laïque selon sa Constitution.',
   'https://fr.wikipedia.org/wiki/La%C3%AFcit%C3%A9'),
 mk('Le contrat social (Rousseau) fonde la légitimité politique sur…','Un pacte par lequel les citoyens s\'associent sous la volonté générale','La force du prince','La tradition uniquement','La richesse',
   '« Du contrat social » (1762) : la souveraineté appartient au peuple ; la loi est l\'expression de la volonté générale.',
   'https://fr.wikipedia.org/wiki/Du_contrat_social'),
 mk('Une ONG est…','Une organisation privée à but non lucratif d\'intérêt public','Une entreprise cotée','Un ministère','Une banque centrale',
   'Les organisations non gouvernementales opèrent dans l\'humanitaire, le développement, l\'environnement, avec des financements mixtes.',
   'https://fr.wikipedia.org/wiki/Organisation_non_gouvernementale'),
 mk('Le pluralisme politique suppose…','La coexistence de plusieurs partis et opinions en compétition libre','Le parti unique','La censure générale','L\'unanimité forcée',
   'Reconnu par la Constitution togolaise de 1992, il conditionne des élections compétitives et la liberté d\'expression.',
   'https://fr.wikipedia.org/wiki/Pluralisme_(politique)'),
 mk('La décentralisation consiste à…','Transférer des compétences de l\'État vers des collectivités élues','Supprimer les communes','Concentrer tous les pouvoirs','Privatiser la justice',
   'Le Togo a relancé sa décentralisation avec les élections municipales de 2019, les premières depuis 1987.',
   'https://fr.wikipedia.org/wiki/D%C3%A9centralisation'),
 mk('Le développement participatif suppose…','L\'implication des populations dans le diagnostic, les choix et le suivi','Des décisions imposées d\'en haut','L\'exclusion des femmes','Le secret des budgets',
   'La participation renforce pertinence, appropriation et durabilité des projets (approches CDD, budgets participatifs).',
   'https://fr.wikipedia.org/wiki/D%C3%A9veloppement_participatif'),
] .forEach(x => soc.push(x));
// Paramétriques : taux de participation électorale (10)
[[3200000,1920000,60],[2500000,1750000,70],[4000000,2600000,65],[1800000,990000,55],[3600000,2880000,80],[2000000,1500000,75],[3000000,1350000,45],[4200000,2100000,50],[2800000,1960000,70],[1500000,1200000,80]]
.forEach(([insc, vot, tx]) => soc.push(mk(
  `Sur ${F(insc)} électeurs inscrits, ${F(vot)} ont voté. Le taux de participation est de :`,
  `${tx} %`, `${Math.max(5,tx-15)} %`, `${Math.min(99,tx+12)} %`, `${100-tx} %`,
  `Participation = votants ÷ inscrits = ${F(vot)} ÷ ${F(insc)} = ${tx} % ; l'abstention est donc de ${100-tx} %.`,
  'https://fr.wikipedia.org/wiki/Taux_de_participation')));
// Répartition des sièges simple (8)
[[60,40,100,60],[45,30,75,60],[80,20,100,80],[52,48,100,52],[66,34,100,66],[75,50,125,60],[90,60,150,60],[70,30,100,70]]
.forEach(([s1, s2, tot, pct]) => soc.push(mk(
  `Un parti obtient ${s1} sièges sur ${tot} au parlement. Sa part des sièges est de :`,
  `${pct} %`, `${Math.max(5,pct-18)} %`, `${Math.min(99,pct+15)} %`, `${100-pct} %`,
  `Part = ${s1} ÷ ${tot} = ${pct} % ${pct>50?'(majorité absolue)':'(pas de majorité absolue)'}.`,
  'https://fr.wikipedia.org/wiki/Syst%C3%A8me_%C3%A9lectoral')));
// Indice de parité filles/garçons (8)
[[90,100,0.9],[100,100,1],[80,100,0.8],[95,100,0.95],[105,100,1.05],[70,100,0.7],[88,110,0.8],[120,100,1.2]]
.forEach(([f, g, ip]) => soc.push(mk(
  `${f} filles et ${g} garçons sont scolarisés dans un cycle. L'indice de parité filles/garçons est de :`,
  `${String(ip).replace('.', ',')}`, `${String(Math.min(2,+(ip+0.3).toFixed(2))).replace('.', ',')}`, `${String(Math.max(0.1,+(ip-0.3).toFixed(2))).replace('.', ',')}`, `${g-f>=0?g-f:f-g}`,
  `Indice = filles ÷ garçons = ${f} ÷ ${g} = ${String(ip).replace('.', ',')} ; 1 = parité parfaite (cible ODD 4).`,
  'https://fr.wikipedia.org/wiki/Indice_de_parit%C3%A9_entre_les_sexes')));

// -------- CULTURE GÉNÉRALE & ENVIRONNEMENT (+112) ---------------------
const cult = [];
[
 mk('Quelle est la capitale du Togo ?','Lomé','Kara','Sokodé','Atakpamé',
   'Lomé, sur le golfe de Guinée, est la capitale politique et économique, dotée d\'un port en eau profonde stratégique pour l\'hinterland sahélien.',
   'https://fr.wikipedia.org/wiki/Lom%C3%A9'),
 mk('Combien de régions administratives compte le Togo ?','5 (Maritime, Plateaux, Centrale, Kara, Savanes)','3','7','10',
   'Du sud au nord : Maritime, Plateaux, Centrale, Kara et Savanes — auxquelles s\'ajoute le district autonome du Grand Lomé.',
   'https://fr.wikipedia.org/wiki/R%C3%A9gions_du_Togo'),
 mk('Le point culminant du Togo est…','Le mont Agou (986 m)','Le mont Kilimandjaro','Le pic d\'Atakora','Le mont Cameroun',
   'Le mont Agou, dans la région des Plateaux près de Kpalimé, culmine à 986 m.',
   'https://fr.wikipedia.org/wiki/Mont_Agou'),
 mk('Quel fleuve principal traverse le Togo ?','Le Mono','Le Niger','Le Congo','La Volta Blanche',
   'Le Mono, long d\'environ 400 km, se jette dans le golfe de Guinée et alimente le barrage de Nangbéto.',
   'https://fr.wikipedia.org/wiki/Mono_(fleuve)'),
 mk('Quels pays bordent le Togo ?','Ghana à l\'ouest, Bénin à l\'est, Burkina Faso au nord','Nigeria et Mali','Côte d\'Ivoire et Niger','Sénégal et Bénin',
   'Le Togo s\'étire sur ~650 km du golfe de Guinée au Burkina Faso, entre Ghana et Bénin.',
   'https://fr.wikipedia.org/wiki/Togo'),
 mk('Le site togolais inscrit au patrimoine mondial de l\'UNESCO est…','Le Koutammakou, pays des Batammariba','Le port de Lomé','La cathédrale de Kara','Le marché d\'Assigamé',
   'Le Koutammakou (2004), avec ses takienta (tours-greniers en terre), illustre un paysage culturel vivant du nord-est du Togo.',
   'https://fr.wikipedia.org/wiki/Koutammakou'),
 mk('L\'hymne national du Togo s\'intitule…','« Salut à toi, pays de nos aïeux »','« Terre de nos ancêtres »','« Ô Togo debout »','« L\'Africaine »',
   'Écrit et composé par Alex Casimir-Dosseh, il fut adopté à l\'indépendance en 1960.',
   'https://fr.wikipedia.org/wiki/Salut_%C3%A0_toi,_pays_de_nos_a%C3%AFeux'),
 mk('Quelle organisation continentale regroupe les 55 États africains ?','L\'Union africaine (UA)','La CEDEAO','L\'ONU','L\'OTAN',
   'Créée en 2002 à Durban (succédant à l\'OUA de 1963), l\'UA siège à Addis-Abeba ; l\'Agenda 2063 fixe sa vision de long terme.',
   'https://fr.wikipedia.org/wiki/Union_africaine'),
 mk('Le siège de l\'ONU se trouve à…','New York','Genève seulement','Paris','Addis-Abeba',
   'Fondée en 1945 par la Charte de San Francisco, l\'ONU a son siège à New York et d\'importants offices à Genève, Vienne et Nairobi.',
   'https://fr.wikipedia.org/wiki/Organisation_des_Nations_unies'),
 mk('Combien d\'États composent l\'UEMOA ?','8','15','5','12',
   'Bénin, Burkina Faso, Côte d\'Ivoire, Guinée-Bissau, Mali, Niger, Sénégal, Togo — unis par le franc CFA et la BCEAO.',
   'https://fr.wikipedia.org/wiki/Union_%C3%A9conomique_et_mon%C3%A9taire_ouest-africaine'),
 mk('L\'effet de serre est causé par…','Des gaz (CO₂, CH₄, N₂O) qui retiennent le rayonnement infrarouge','La rotation de la Terre','Les marées','Le champ magnétique',
   'Naturel et vital, l\'effet de serre est amplifié par les émissions humaines, provoquant le réchauffement climatique.',
   'https://fr.wikipedia.org/wiki/Effet_de_serre'),
 mk('L\'Accord de Paris (2015) vise à contenir le réchauffement…','Bien en dessous de 2 °C, en visant 1,5 °C','À 5 °C','À zéro immédiatement','Sans objectif chiffré',
   'Adopté à la COP21, il repose sur les contributions déterminées au niveau national (CDN), révisées à la hausse périodiquement.',
   'https://fr.wikipedia.org/wiki/Accord_de_Paris_sur_le_climat'),
 mk('Le GIEC est…','Le groupe d\'experts intergouvernemental sur l\'évolution du climat','Une banque','Une ONG militante','Un parti politique',
   'Créé en 1988 (OMM/PNUE), le GIEC synthétise la science du climat ; ses rapports guident les négociations internationales.',
   'https://fr.wikipedia.org/wiki/Groupe_d%27experts_intergouvernemental_sur_l%27%C3%A9volution_du_climat'),
 mk('La biodiversité désigne…','La diversité des gènes, espèces et écosystèmes','Les seuls animaux domestiques','Les minéraux','Les villes',
   'Convention sur la diversité biologique (1992) ; le cadre mondial Kunming-Montréal (2022) vise notamment 30 % d\'aires protégées d\'ici 2030.',
   'https://fr.wikipedia.org/wiki/Biodiversit%C3%A9'),
 mk('La désertification menace particulièrement…','Les zones arides et semi-arides comme le Sahel','Les pôles','Les océans profonds','Les mégapoles européennes',
   'Dégradation des terres liée au climat et aux activités humaines ; la Grande Muraille Verte africaine tente d\'y répondre.',
   'https://fr.wikipedia.org/wiki/D%C3%A9sertification'),
 mk('Les énergies renouvelables incluent…','Solaire, éolien, hydraulique, biomasse, géothermie','Charbon et pétrole','Gaz naturel et uranium seul','Diesel amélioré',
   'Renouvelables car issues de flux naturels inépuisables ; le Togo développe notamment le solaire (centrale de Blitta).',
   'https://fr.wikipedia.org/wiki/%C3%89nergie_renouvelable'),
 mk('Le recyclage relève de l\'économie…','Circulaire (réduire, réutiliser, recycler)','Linéaire','Souterraine','De rente',
   'L\'économie circulaire boucle les flux de matières pour réduire déchets et prélèvements ; opposée au modèle « extraire-produire-jeter ».',
   'https://fr.wikipedia.org/wiki/%C3%89conomie_circulaire'),
 mk('La couche d\'ozone protège la Terre…','Des rayons ultraviolets nocifs','Des séismes','Des marées','Du bruit',
   'Le Protocole de Montréal (1987), succès environnemental mondial, a éliminé l\'essentiel des CFC destructeurs d\'ozone.',
   'https://fr.wikipedia.org/wiki/Couche_d%27ozone'),
 mk('L\'empreinte carbone mesure…','Les émissions de gaz à effet de serre associées à une activité ou un mode de vie','La taille des chaussures','La surface cultivée','Le poids des déchets uniquement',
   'Exprimée en tonnes de CO₂ équivalent ; elle guide les stratégies de réduction et de compensation.',
   'https://fr.wikipedia.org/wiki/Empreinte_carbone'),
 mk('Quel est l\'océan qui borde l\'Afrique de l\'Ouest ?','L\'océan Atlantique','L\'océan Indien','L\'océan Arctique','La mer Caspienne',
   'Le golfe de Guinée, sur l\'Atlantique, borde le Togo ; il concentre ports, pêche et enjeux de sécurité maritime.',
   'https://fr.wikipedia.org/wiki/Golfe_de_Guin%C3%A9e'),
 mk('Le plus long fleuve d\'Afrique est…','Le Nil','Le Congo','Le Niger','Le Zambèze',
   'Le Nil (~6 650 km) devance le Congo (plus puissant en débit) ; le Niger, 3ᵉ, irrigue l\'Afrique de l\'Ouest.',
   'https://fr.wikipedia.org/wiki/Nil'),
 mk('Quel est le pays le plus peuplé d\'Afrique ?','Le Nigeria','L\'Égypte','L\'Éthiopie','L\'Afrique du Sud',
   'Avec plus de 200 millions d\'habitants, le Nigeria est aussi la première économie du continent en PIB nominal.',
   'https://fr.wikipedia.org/wiki/Nigeria'),
 mk('Le désert du Sahara est…','Le plus grand désert chaud du monde','Une forêt tropicale','Un lac asséché récent','Une chaîne de montagnes',
   'S\'étendant sur ~9 millions de km², il sépare l\'Afrique du Nord de l\'Afrique subsaharienne.',
   'https://fr.wikipedia.org/wiki/Sahara'),
 mk('Internet fonctionne grâce au protocole de base…','TCP/IP','HTML seul','USB','Bluetooth',
   'TCP/IP structure l\'adressage et le transport des paquets ; le web (HTTP/HTML) n\'est qu\'un service parmi d\'autres d\'Internet.',
   'https://fr.wikipedia.org/wiki/Suite_des_protocoles_Internet'),
 mk('La monnaie officielle du Togo est…','Le franc CFA (XOF)','L\'éco déjà en circulation','Le cedi','Le naira',
   'Le franc CFA ouest-africain, émis par la BCEAO ; le projet de monnaie unique CEDEAO « éco » reste en préparation.',
   'https://fr.wikipedia.org/wiki/Franc_CFA'),
 mk('Le paludisme est transmis par…','La piqûre du moustique anophèle femelle','L\'eau salée','Le vent','Les poignées de main',
   'Première cause de morbidité dans plusieurs pays africains ; moustiquaires imprégnées, tests rapides et nouveaux vaccins (RTS,S ; R21) font reculer la maladie.',
   'https://fr.wikipedia.org/wiki/Paludisme'),
 mk('La journée mondiale de l\'environnement est célébrée le…','5 juin','1ᵉʳ janvier','25 décembre','14 juillet',
   'Instituée par l\'ONU en 1972 (conférence de Stockholm), elle mobilise chaque année autour d\'un thème environnemental.',
   'https://fr.wikipedia.org/wiki/Journ%C3%A9e_mondiale_de_l%27environnement'),
 mk('Le « poumon vert » de la planète désigne souvent…','La forêt amazonienne','Le Sahara','L\'Antarctique','La Sibérie urbaine',
   'Plus grande forêt tropicale du monde, l\'Amazonie stocke un carbone considérable ; le bassin du Congo joue un rôle comparable en Afrique.',
   'https://fr.wikipedia.org/wiki/For%C3%AAt_amazonienne'),
] .forEach(x => cult.push(x));
// Paramétriques environnement/énergie (émissions, conversions) (12)
[[120,0.5,60],[200,0.5,100],[80,0.25,20],[300,0.2,60],[150,0.4,60],[240,0.25,60],[400,0.15,60],[100,0.35,35],[180,0.5,90],[260,0.25,65],[90,0.2,18],[500,0.1,50]]
.forEach(([kwh, kg, tot]) => cult.push(mk(
  `Un ménage consomme ${F(kwh)} kWh d'électricité dans le mois, avec un facteur d'émission de ${String(kg).replace('.', ',')} kg CO₂/kWh. Émissions mensuelles :`,
  `${F(tot)} kg CO₂`, `${F(tot*2)} kg CO₂`, `${F(Math.round(tot/2))} kg CO₂`, `${F(kwh)} kg CO₂`,
  `Émissions = ${F(kwh)} × ${String(kg).replace('.', ',')} = ${F(tot)} kg de CO₂.`,
  'https://fr.wikipedia.org/wiki/Empreinte_carbone')));
// Taux de couverture forestière (8)
[[5600,56000,10],[12000,60000,20],[9000,45000,20],[3000,60000,5],[15000,50000,30],[7200,48000,15],[24000,60000,40],[4500,90000,5]]
.forEach(([f, s, tx]) => cult.push(mk(
  `Un pays possède ${F(f)} km² de forêts pour une superficie de ${F(s)} km². Son taux de couverture forestière est de :`,
  `${tx} %`, `${tx*2} %`, `${Math.max(1,Math.round(tx/2))} %`, `${100-tx} %`,
  `Taux = forêts ÷ superficie = ${F(f)} ÷ ${F(s)} = ${tx} %.`,
  'https://fr.wikipedia.org/wiki/Taux_de_boisement')));
// Gestion des déchets : taux de recyclage (8)
[[30,150,20],[45,180,25],[60,200,30],[25,250,10],[90,300,30],[40,160,25],[75,150,50],[36,240,15]]
.forEach(([r, t, tx]) => cult.push(mk(
  `Sur ${F(t)} tonnes de déchets collectés, ${F(r)} tonnes sont recyclées. Le taux de recyclage est de :`,
  `${tx} %`, `${Math.min(95,tx+20)} %`, `${Math.max(2,tx-8)} %`, `${100-tx} %`,
  `Taux = recyclé ÷ collecté = ${F(r)} ÷ ${F(t)} = ${tx} %.`,
  'https://fr.wikipedia.org/wiki/Recyclage')));
// Capitales africaines (12)
[['Ghana','Accra','Kumasi','Tamale','Takoradi'],['Bénin','Porto-Novo (Cotonou siège du gouvernement)','Parakou','Abomey','Natitingou'],
 ['Burkina Faso','Ouagadougou','Bobo-Dioulasso','Koudougou','Banfora'],['Côte d\'Ivoire','Yamoussoukro (Abidjan capitale économique)','Bouaké','Daloa','San-Pédro'],
 ['Sénégal','Dakar','Thiès','Saint-Louis','Ziguinchor'],['Mali','Bamako','Sikasso','Mopti','Kayes'],
 ['Niger','Niamey','Zinder','Maradi','Agadez'],['Nigeria','Abuja (Lagos capitale économique)','Kano','Ibadan','Port Harcourt'],
 ['Kenya','Nairobi','Mombasa','Kisumu','Nakuru'],['Éthiopie','Addis-Abeba','Dire Dawa','Mekele','Gondar'],
 ['Maroc','Rabat (Casablanca capitale économique)','Fès','Marrakech','Tanger'],['Afrique du Sud','Pretoria (exécutif ; Le Cap législatif)','Durban','Johannesburg seul','Bloemfontein seul']]
.forEach(([pays, cap, w1, w2, w3]) => cult.push(mk(
  `Quelle est la capitale (politique) du ${pays.startsWith('Afrique')||pays.startsWith('Éthiopie')?'de l\''+pays.replace('Éthiopie','Éthiopie'):pays} ?`.replace('du de l\'','de l\''),
  cap, w1, w2, w3,
  `${cap.split(' (')[0]} est la capitale du ${pays}.`.replace('du Afrique','de l\'Afrique').replace('du Éthiopie','de l\'Éthiopie'),
  'https://fr.wikipedia.org/wiki/Liste_des_capitales_du_monde')));

module.exports = { soc, cult };
